In [1]:
import gc
import torch
import shutil
import os
import glob
from pathlib import Path

# 1. Clear GPU Memory
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print(f"GPU Memory Cleared. Currently allocated: {torch.cuda.memory_allocated() / 1024**2:.2f} MB")

# 2. Run Garbage Collection
gc.collect()

# 3. Redirect HF cache to a local folder instead of Google Drive
HF_CACHE_DIR = os.path.join(os.getcwd(), 'hf_cache')
os.environ['HF_HOME'] = HF_CACHE_DIR
os.makedirs(os.environ['HF_HOME'], exist_ok=True)

# 4. Clean up local disk (Temporary results directories)
for results_dir in glob.glob('./results_*'):
    if os.path.exists(results_dir):
        print(f"Removing temporary directory: {results_dir}")
        shutil.rmtree(results_dir)

if os.path.exists('./runs'):
    shutil.rmtree('./runs')

print(f"Memory and local disk cleanup complete. HF Cache redirected to: {os.environ['HF_HOME']}")

GPU Memory Cleared. Currently allocated: 0.00 MB
Memory and local disk cleanup complete. HF Cache redirected to: d:\Nepali sentiment\hf_cache

# Devnagiri Text — Sentiment Classification (XLM-R / MuRIL / mBERT)

This notebook fine-tunes and compares **three** multilingual transformer models — `xlm-roberta-base`, `google/muril-base-cased`, and `bert-base-multilingual-cased` — on the `English_Translation` column for **3-class sentiment classification** (Positive / Neutral / Negative).




### One pipeline, three independent runs
All three models are trained through **one shared function**, `run_sentiment_pipeline(model_key, model_name)`. Each call is fully self-contained (own tokenizer, own model, own trainer, own save directory) — so you run whichever model you need, in any order, without the others being trained first:
```python
results['XLM-R'] = run_sentiment_pipeline('xlmr',  'xlm-roberta-base')
results['MuRIL'] = run_sentiment_pipeline('muril', 'google/muril-base-cased')
results['mBERT'] = run_sentiment_pipeline('mbert', 'bert-base-multilingual-cased')
```
```
Dataset  : Combined_Common_File.xlsx
Input col: input_text (English_Translation column, mapped from source file)
Label col: sentiment  (Positive / Neutral / Negative)
```

## 0. Mount Drive & GPU Check

In [2]:
# Local-device notebook: Colab Drive mount is not required.
print('Local notebook environment active; Google Drive mount skipped.')

Local notebook environment active; Google Drive mount skipped.

In [3]:
import torch
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("WARNING: No GPU detected — training will be very slow!")

GPU Available: True
GPU Name: NVIDIA GeForce RTX 4060 Laptop GPU

## 1. Imports

In [4]:
!pip install -q evaluate

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# Install missing libraries
!pip install -q evaluate

import os
import gc
import shutil
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainerCallback,
    TrainingArguments,
    EarlyStoppingCallback,
)
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import evaluate
import warnings
warnings.filterwarnings('ignore')

print("All imports OK")

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

All imports OK

In [6]:
!pip install -q optuna

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 2. Configuration

In [7]:
from huggingface_hub import login

login()

In [8]:
# ── Paths ─────────────────────────────────────────────────────────────────────

# Local data source
TRAIN_PATH = r"D:\Nepali sentiment\train_devanagari.xlsx"
VAL_PATH = r"D:\Nepali sentiment\val_devanagari.xlsx"
TEST_PATH = r"D:\Nepali sentiment\test_devanagari.xlsx"

# ============================================================
# D: DRIVE STORAGE
# ============================================================

D_ROOT = r'D:\Nepali sentiment'

# Main directories
MODEL_ROOT = os.path.join(D_ROOT, 'models')
TOKENIZER_ROOT = os.path.join(D_ROOT, 'tokenizers')
RESULTS_ROOT = os.path.join(D_ROOT, 'results')
TRAINING_ROOT = os.path.join(D_ROOT, 'training_checkpoints')

# Hugging Face cache
HF_ROOT = os.path.join(D_ROOT, 'hf_cache')

os.environ['HF_HOME'] = HF_ROOT
os.environ['HF_HUB_CACHE'] = os.path.join(HF_ROOT, 'hub')
os.environ['TRANSFORMERS_CACHE'] = os.path.join(HF_ROOT, 'transformers')

# Try a Hub login only if a valid token is available locally.
# If the environment is offline or the token cannot be validated, we still continue
# # with the local cache and already downloaded model files.
# try:
#     from huggingface_hub import login
#     hf_token = os.environ.get('HF_TOKEN')
#     if hf_token:
#         login(token=hf_token, add_to_git_credential=False)
#         print('Hugging Face login successful using HF_TOKEN.')
#     else:
#         print('HF_TOKEN not found; continuing in offline/cache mode.')
# except Exception as exc:
#     print(f'Hugging Face login skipped: {exc}')
#     print('Continuing with local cache / already-downloaded models.')

# Create all directories
for folder in [
    D_ROOT,
    MODEL_ROOT,
    TOKENIZER_ROOT,
    RESULTS_ROOT,
    TRAINING_ROOT,
    HF_ROOT,
    os.environ['HF_HUB_CACHE'],
    os.environ['TRANSFORMERS_CACHE'],
]:
    os.makedirs(folder, exist_ok=True)

print("=" * 70)
print("D: DRIVE STORAGE CONFIGURED")
print("=" * 70)
print(f"Root directory       : {D_ROOT}")
print(f"Models               : {MODEL_ROOT}")
print(f"Tokenizers           : {TOKENIZER_ROOT}")
print(f"Results              : {RESULTS_ROOT}")
print(f"Checkpoints          : {TRAINING_ROOT}")
print(f"HuggingFace cache    : {HF_ROOT}")
print("=" * 70)


# ── Label mapping ─────────────────────────────────────────────────────────────

# Paper (Thapa et al. 2023) uses Positive / Neutral / Negative

SENT_MAP = {
    'Positive': 0,
    'Neutral': 1,
    'Negative': 2,
}

ID2LABEL = {v: k for k, v in SENT_MAP.items()}
N_LABELS = len(SENT_MAP)


# ── Shared training hyper-parameters ──────────────────────────────────────────

MAX_LEN             = 256
SEED                = 42
EPOCHS              = 5
BATCH_TRAIN         = 16
BATCH_EVAL          = 32
LR                  = 1e-5
WEIGHT_DECAY        = 0.15
WARMUP_RATIO        = 0.1
GRAD_ACCUM          = 2
EARLY_STOP_PATIENCE = 2
SAVE_TOTAL_LIMIT    = 1


# ── The 3 models being compared ──────────────────────────────────────────────

MODEL_CONFIGS = [
    {
        'key': 'xlmr',
        'label': 'XLM-RoBERTa',
        'checkpoint': 'xlm-roberta-base',

        # Final trained model → D:
        'save_dir': os.path.join(
            MODEL_ROOT,
            'xlm-roberta-base_model'
        ),

        # Tokenizer → D:
        'tok_dir': os.path.join(
            TOKENIZER_ROOT,
            'xlm-roberta-base_tokenizer'
        ),

        # Trainer checkpoints/results → D:
        'output_dir': os.path.join(
            TRAINING_ROOT,
            'xlmr'
        ),
    },

    {
        'key': 'mbert',
        'label': 'mBERT',
        'checkpoint': 'bert-base-multilingual-cased',

        'save_dir': os.path.join(
            MODEL_ROOT,
            'mbert_sentiment_model'
        ),

        'tok_dir': os.path.join(
            TOKENIZER_ROOT,
            'mbert_sentiment_tokenizer'
        ),

        'output_dir': os.path.join(
            TRAINING_ROOT,
            'mbert'
        ),
    },

    {
        'key': 'muril',
        'label': 'MuRIL',
        'checkpoint': 'google/muril-base-cased',

        'save_dir': os.path.join(
            MODEL_ROOT,
            'muril_sentiment_model'
        ),

        'tok_dir': os.path.join(
            TOKENIZER_ROOT,
            'muril_sentiment_tokenizer'
        ),

        'output_dir': os.path.join(
            TRAINING_ROOT,
            'muril'
        ),
    },
]


print("\nModels configured:")
for c in MODEL_CONFIGS:
    print(
        f"  - {c['label']:<15} → {c['checkpoint']}"
    )
    print(
        f"      Model     : {c['save_dir']}"
    )
    print(
        f"      Tokenizer : {c['tok_dir']}"
    )
    print(
        f"      Training  : {c['output_dir']}"
    )

======================================================================
D: DRIVE STORAGE CONFIGURED
======================================================================
Root directory       : D:\Nepali sentiment
Models               : D:\Nepali sentiment\models
Tokenizers           : D:\Nepali sentiment\tokenizers
Results              : D:\Nepali sentiment\results
Checkpoints          : D:\Nepali sentiment\training_checkpoints
HuggingFace cache    : D:\Nepali sentiment\hf_cache
======================================================================

Models configured:
  - XLM-RoBERTa     → xlm-roberta-base
      Model     : D:\Nepali sentiment\models\xlm-roberta-base_model
      Tokenizer : D:\Nepali sentiment\tokenizers\xlm-roberta-base_tokenizer
      Training  : D:\Nepali sentiment\training_checkpoints\xlmr
  - mBERT           → bert-base-multilingual-cased
      Model     : D:\Nepali sentiment\models\mbert_sentiment_model
      Tokenizer : D:\Nepali sentiment\tokenizers\mbert_sentiment_tokenizer
      Training  : D:\Nepali sentiment\training_checkpoints\mbert
  - MuRIL           → google/muril-base-cased
      Model     : D:\Nepali sentiment\models\muril_sentiment_model
      Tokenizer : D:\Nepali sentiment\tokenizers\muril_sentiment_tokenizer
      Training  : D:\Nepali sentiment\training_checkpoints\muril

```markdown
## 2.1. Data Consolidation
Combining multiple Excel sources into a single dataset for training and validation.
```

## 3. Data Loading & Preprocessing

In [9]:
import pandas as pd
import os


def prepare_dataset(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Cannot find file at {path}.")

    df = pd.read_excel(path) if path.endswith(('.xlsx', '.xls')) else pd.read_csv(path)

    target_text_col = 'Nepali_Translation'
    target_label_col = 'Sentiment'

    if target_text_col in df.columns and target_label_col in df.columns:
        df = df[[target_text_col, target_label_col]].copy()
    else:
        df = df.iloc[:, [3, 2]].copy()

    df.columns = ['input_text', 'sentiment_raw']
    df = df.dropna().reset_index(drop=True)

    df['sentiment_raw'] = (
        df['sentiment_raw']
        .astype(str)
        .str.strip()
        .str.capitalize()
        .replace({'Postive': 'Positive', 'Netural': 'Neutral'})
    )

    df['label'] = df['sentiment_raw'].map(SENT_MAP)
    df = df[df['label'].notna()].reset_index(drop=True)
    df['label'] = df['label'].astype(int)

    # Remove duplicate texts within each split before comparing splits.
    return df.drop_duplicates(subset=['input_text'], keep='first').reset_index(drop=True)


# ── Load datasets ──────────────────────────────────────────────
print("Loading specific datasets...")
train_df = prepare_dataset(TRAIN_PATH)
val_df   = prepare_dataset(VAL_PATH)
test_df  = prepare_dataset(TEST_PATH)

print("\nBefore cross-split dedup:")
print(f"  Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

# ── Cross-split deduplication ──────────────────────────────────
# Priority: train > val > test.
train_texts = set(train_df['input_text'].astype(str))
val_df = val_df[
    ~val_df['input_text'].astype(str).isin(train_texts)
].reset_index(drop=True)

train_val_texts = train_texts | set(val_df['input_text'].astype(str))
test_df = test_df[
    ~test_df['input_text'].astype(str).isin(train_val_texts)
].reset_index(drop=True)

print("\nAfter cross-split dedup:")
print(f"  Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

# ── Verify zero leakage ────────────────────────────────────────
t_set = set(train_df['input_text'].astype(str))
v_set = set(val_df['input_text'].astype(str))
e_set = set(test_df['input_text'].astype(str))
leakage = {
    'train_val': len(t_set & v_set),
    'train_test': len(t_set & e_set),
    'val_test': len(v_set & e_set),
}
print(f"  Leakage check: {leakage}")
assert all(value == 0 for value in leakage.values()), "Leakage still present!"
print("  ✅ Zero leakage confirmed.\n")

print("Successfully loaded datasets with zero cross-split leakage.")

Loading specific datasets...

Before cross-split dedup:
  Train: 8549 | Val: 1070 | Test: 1069

After cross-split dedup:
  Train: 8549 | Val: 1069 | Test: 1069
  Leakage check: {'train_val': 0, 'train_test': 0, 'val_test': 0}
  ✅ Zero leakage confirmed.

Successfully loaded datasets with zero cross-split leakage.

## 4. Train / Validation / Test Split

Stratified 80/10/10 split on the label column — computed once and shared by every model so the comparison across XLM-R / MuRIL / mBERT is apples-to-apples.

In [10]:
# The datasets were already loaded separately above by prepare_dataset().
# Do not split an undefined combined dataframe here.
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

# Safety check: if the same raw text appears across splits, report it.
train_texts = set(train_df['input_text'].astype(str))
val_texts = set(val_df['input_text'].astype(str))
test_texts = set(test_df['input_text'].astype(str))
leakage = {
    'train_val': len(train_texts & val_texts),
    'train_test': len(train_texts & test_texts),
    'val_test': len(val_texts & test_texts),
}

print(f"Train : {len(train_df)} rows")
print(f"Val   : {len(val_df)} rows")
print(f"Test  : {len(test_df)} rows")
print(f"Cross-split overlap after deduplication: {leakage}")
print("\nTrain distribution:")
print(train_df['sentiment_raw'].value_counts())
print("\nVal distribution:")
print(val_df['sentiment_raw'].value_counts())
print("\nTest distribution:")
print(test_df['sentiment_raw'].value_counts())

Train : 8549 rows
Val   : 1069 rows
Test  : 1069 rows
Cross-split overlap after deduplication: {'train_val': 0, 'train_test': 0, 'val_test': 0}

Train distribution:
sentiment_raw
Neutral     2911
Negative    2870
Positive    2768
Name: count, dtype: int64

Val distribution:
sentiment_raw
Neutral     364
Negative    360
Positive    345
Name: count, dtype: int64

Test distribution:
sentiment_raw
Neutral     365
Negative    359
Positive    345
Name: count, dtype: int64

In [11]:
train_df.head(3), val_df.head(3), test_df.head(3)

(                                          input_text sentiment_raw  label
 0  यस्तो सालो मिडिया मादरचोद त्यत्तिकै आइमाई बोल्...      Negative      2
 1  सोनिकाको अन्तर्वार्ता साह्रै मन पर्छ उहाँको बो...      Positive      0
 2                        थुक्क माचिक्ने लोकतन्त्र 😠😟      Negative      2,
                                           input_text sentiment_raw  label
 0         इन्टरभ्युको लागि हार्दिक आभार टिकाराम सर 🙏      Positive      0
 1              के गर्नु बुढी कमजोर भएपछि दुःख पाइन्छ      Negative      2
 2  यसो त्यो राँडीको किन इन्टरभ्यु लिएर आएको होला ...      Negative      2,
                                           input_text sentiment_raw  label
 0            वास्तवमै सही व्यक्ति दिनेश शर्मा रेग्मी      Positive      0
 1  कुनै हिरोहरूमा मलाई सबैभन्दा मन पर्ने दिनेश सा...      Positive      0
 2  अमित र प्रितीको आजको प्रस्तुति निकै राम्रो थिय...      Positive      0)

## 5. Dataset Class

Tokenization is model-specific (each model has its own tokenizer/vocab), so it happens inside `run_sentiment_pipeline` below rather than as a separate global step — but the `Dataset` wrapper itself is identical for every model.

In [12]:
class SentimentDataset(torch.utils.data.Dataset):
    def __init__(self, encodings: dict, labels: list):
        self.encodings = encodings
        self.labels    = labels

    def __getitem__(self, idx: int) -> dict:
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self) -> int:
        return len(self.labels)

print("SentimentDataset defined.")

SentimentDataset defined.

## 6. Class Weights

Computed once from `train_df` and reused by every model — the label distribution doesn't change between models, only the tokenizer/architecture does.

In [13]:
cw = compute_class_weight(
    class_weight='balanced',
    classes=np.array([0, 1, 2]),
    y=train_df['label'].tolist(),
)
class_weights = torch.tensor(cw, dtype=torch.float)
print(f"Class weights (Pos / Neu / Neg): {class_weights.numpy().round(4)}")

Class weights (Pos / Neu / Neg): [1.0295 0.9789 0.9929]

## 7. Custom Trainer with Class-Weighted Loss

We override `compute_loss` to pass `class_weights` to `CrossEntropyLoss`, giving heavier penalty to misclassified minority examples. Same trainer class used for all three models.

In [14]:
import torch.nn as nn

class FocalLoss(nn.Module):
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.alpha = alpha
        self.reduction = reduction

    def forward(self, inputs, targets):
        # Calculate standard cross-entropy loss without reduction
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        # Get the probability of the true class
        pt = torch.exp(-ce_loss)
        # Apply the focal loss modulating factor
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss

        # Apply class weights (alpha) if provided
        if self.alpha is not None:
            alpha_weights = self.alpha.to(targets.device)[targets]
            focal_loss = alpha_weights * focal_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        return focal_loss

class EpochLossPrinter(TrainerCallback):
    """Prints training and validation loss at the end of each epoch."""
    
    def on_epoch_end(self, args, state, control, **kwargs):
        epoch = int(state.epoch)
        
        # Get training loss from the current epoch
        train_loss = None
        val_loss = None
        val_f1 = None
        
        for log in state.log_history:
            if "loss" in log and "eval_loss" not in log:
                if abs(log.get("epoch", 0) - epoch) < 0.01:
                    train_loss = log["loss"]
            if "eval_loss" in log:
                if abs(log.get("epoch", 0) - epoch) < 0.01:
                    val_loss = log["eval_loss"]
                    val_f1 = log.get("eval_macro_f1", None)
        
        print(f"\n  📊 Epoch {epoch}/{args.num_train_epochs}")
        if train_loss is not None:
            print(f"     Train Loss : {train_loss:.4f}")
        if val_loss is not None:
            print(f"     Val Loss   : {val_loss:.4f}")
        if val_f1 is not None:
            print(f"     Val F1     : {val_f1:.4f}")
        
class WeightedTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.criterion = FocalLoss(alpha=class_weights, gamma=2.0)

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop('labels')
        outputs = model(**inputs)
        logits = outputs.logits

        # Compute focal loss instead of cross_entropy
        loss = self.criterion(logits, labels)

        return (loss, outputs) if return_outputs else loss

In [15]:
class CustomSentimentHead(nn.Module):
    def __init__(self, hidden_size, num_labels):
        super().__init__()
        self.dropouts = nn.ModuleList([nn.Dropout(0.2) for _ in range(5)])
        self.classifier = nn.Linear(hidden_size, num_labels)

    def forward(self, pooled_output):
        # Multi-Sample Dropout: Average logits from 5 different dropout masks
        logits_list = [self.classifier(dropout(pooled_output)) for dropout in self.dropouts]
        return torch.stack(logits_list, dim=0).mean(dim=0)

class CustomSentimentModel(nn.Module):
    def __init__(self, checkpoint, num_labels, id2label, label2id):
        super().__init__()
        from transformers import AutoModel
        self.num_labels = num_labels
        self.id2label = id2label
        self.label2id = label2id

        # Load backbone
        self.backbone = AutoModel.from_pretrained(checkpoint)
        hidden_size = self.backbone.config.hidden_size

        # Custom Head
        self.classifier = CustomSentimentHead(hidden_size, num_labels)

    def gradient_checkpointing_enable(self, **kwargs):
        """Delegate gradient checkpointing to the backbone transformer."""
        if hasattr(self.backbone, "gradient_checkpointing_enable"):
            self.backbone.gradient_checkpointing_enable(**kwargs)

    def forward(self, input_ids=None, attention_mask=None, token_type_ids=None, labels=None, **kwargs):
        outputs = self.backbone(input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids, **kwargs)

        # Use pooled output (usually [CLS] token representation)
        pooled_output = outputs.pooler_output if hasattr(outputs, 'pooler_output') else outputs.last_hidden_state[:, 0]

        logits = self.classifier(pooled_output)

        loss = None
        # Note: Loss calculation is handled by the WeightedTrainer using FocalLoss

        from transformers.modeling_outputs import SequenceClassifierOutput
        return SequenceClassifierOutput(loss=loss, logits=logits, hidden_states=outputs.hidden_states, attentions=outputs.attentions)

## 8. Metrics

We track **accuracy** and **macro-F1** during training, and produce a full `classification_report` at the end — same metrics reported in Thapa et al. (2023).

In [16]:
from sklearn.metrics import accuracy_score, f1_score


def compute_metrics(eval_pred):
    logits, labels = eval_pred

    if isinstance(logits, tuple):
        logits = logits[0]

    predictions = np.argmax(logits, axis=-1)

    return {
        "accuracy": float(accuracy_score(labels, predictions)),
        "macro_f1": float(f1_score(
            labels,
            predictions,
            average="macro",
            zero_division=0,
        )),
        "micro_f1": float(f1_score(
            labels,
            predictions,
            average="micro",
            zero_division=0,
        )),
        "weighted_f1": float(f1_score(
            labels,
            predictions,
            average="weighted",
            zero_division=0,
        )),
    }

In [17]:
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

def plot_multiclass_roc(all_labels, all_probs, label_names, title='ROC Curve'):
    """
    Plots a multi-class ROC curve using the One-vs-Rest strategy.
    """
    n_classes = len(label_names)
    # Binarize labels for multi-class ROC
    y_test_bin = label_binarize(all_labels, classes=range(n_classes))

    fpr = dict()
    tpr = dict()
    roc_auc = dict()

    plt.figure(figsize=(8, 6))
    colors = ['#4C72B0', '#55A868', '#C44E52']

    for i in range(n_classes):
        fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], all_probs[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

        plt.plot(fpr[i], tpr[i], color=colors[i], lw=2,
                 label=f'ROC {label_names[i]} (area = {roc_auc[i]:.2f})')

    plt.plot([0, 1], [0, 1], 'k--', lw=1, alpha=0.5)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(title)
    plt.legend(loc="lower right")
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()

## 9. Pipeline Helpers

Two small utilities the training function relies on:
- `get_precision_kwargs()` checks what the *current* GPU actually supports instead of hardcoding `bf16=True` — a T4 (common on free-tier Colab) doesn't support bf16 and would raise an error on it, while an A100/L4 does.
- `free_memory()` clears GPU cache and runs garbage collection between models, so the second and third model don't fight the first one for GPU memory.

In [18]:
def get_precision_kwargs() -> dict:
    """
    Picks the fastest safe mixed-precision setting for the current hardware.
    Tesla T4 (free Colab) does NOT support bf16.
    """
    if not torch.cuda.is_available():
        return {'fp16': False, 'bf16': False}

    # Explicit check for compute capability: bf16 requires >= 8.0 (Ampere+)
    # T4 is 7.5 (Turing), so it must use fp16.
    if torch.cuda.get_device_capability()[0] >= 8:
        try:
            if torch.cuda.is_bf16_supported():
                return {'fp16': False, 'bf16': True}
        except Exception:
            pass

    return {'fp16': True, 'bf16': False}

print("Precision setting for this runtime:", get_precision_kwargs())

Precision setting for this runtime: {'fp16': False, 'bf16': True}

In [19]:
def get_optimizer_params(model, learning_rate, weight_decay, layer_decay=0.9):
    """
    Groups model parameters with layer-wise learning rate decay.
    Lower layers get a smaller learning rate.
    """
    no_decay = ['bias', 'LayerNorm.weight', 'LayerNorm.bias']
    optimizer_grouped_parameters = []

    # 1. Classification head (Maximum LR)
    head_params = [p for n, p in model.named_parameters() if 'classifier' in n or 'pooler' in n]
    if head_params:
        optimizer_grouped_parameters.append({
            'params': head_params,
            'lr': learning_rate,
            'weight_decay': weight_decay
        })

    # 2. Transformer Layers (Decaying LR)
    # Most architectures (BERT, RoBERTa, MuRIL) use 'layer.i' in their naming convention
    for layer_idx in range(11, -1, -1):
        layer_lr = learning_rate * (layer_decay ** (11 - layer_idx))

        optimizer_grouped_parameters.extend([
            {
                'params': [p for n, p in model.named_parameters() if f'layer.{layer_idx}.' in n and not any(nd in n for nd in no_decay)],
                'lr': layer_lr,
                'weight_decay': weight_decay
            },
            {
                'params': [p for n, p in model.named_parameters() if f'layer.{layer_idx}.' in n and any(nd in n for nd in no_decay)],
                'lr': layer_lr,
                'weight_decay': 0.0
            }
        ])

    # 3. Embeddings (Lowest LR)
    embed_params = [p for n, p in model.named_parameters() if 'embeddings' in n]
    if embed_params:
        optimizer_grouped_parameters.append({
            'params': embed_params,
            'lr': learning_rate * (layer_decay ** 12),
            'weight_decay': weight_decay
        })

    return optimizer_grouped_parameters

## 10. Unified Training Pipeline

This is the piece that was missing for mBERT and MuRIL: **one function**, used for every model, that tokenizes, builds datasets, initializes the model, trains with `WeightedTrainer`, evaluates, plots a confusion matrix, saves to Drive, and cleans up — always in that order, so evaluation and saving always happen *before* anything gets deleted.

In [20]:
"""
RESEARCH-GRADE SENTIMENT PIPELINE — v6.1 (SPEED-OPTIMIZED, SINGLE SEED)
=========================================================================

Changes from v6:
  [SPEED]  Single seed only (no multi-seed loop)
  [SPEED]  gradient_checkpointing OFF by default (configurable)
  [SPEED]  dataloader_num_workers=0 (avoids Windows/Jupyter deadlock)
  [SPEED]  Train diagnostics on SUBSET (default 1000 samples)
  [SPEED]  save_only_model=True (smaller checkpoints, faster I/O)
  [SPEED]  save_total_limit=1 (less disk writes)
  [SPEED]  batch_size=32, grad_accum=1 (configurable)
  [SPEED]  Sampled token-length analysis (5000 samples)
  [SPEED]  tf32=True + auto bf16/fp16
  [SPEED]  logging_strategy="steps" for live progress visibility
  [KEEP]   Dynamic padding via DataCollatorWithPadding
  [KEEP]   Early stopping, best-checkpoint loading
  [KEEP]   Bootstrap CI, ECE, ROC, error analysis (on TEST only)

Assumes the following exist earlier in your notebook/module:
    Constants:
        MAX_LEN, SEED, EPOCHS, EARLY_STOP_PATIENCE,
        GRAD_ACCUM, BATCH_TRAIN, BATCH_EVAL,
        LR, WEIGHT_DECAY, N_LABELS, ID2LABEL, SENT_MAP
    Classes:
        SentimentDataset, CustomSentimentModel, WeightedTrainer
    Functions:
        get_optimizer_params(model, lr, weight_decay, layer_decay=...),
        get_precision_kwargs(), compute_metrics(eval_pred)
"""

import os
import gc
import sys
import json
import shutil
import random
from datetime import datetime

import numpy as np
import pandas as pd
import torch
import optuna
import transformers
import sklearn
import math
import matplotlib
matplotlib.use("Agg")  # headless-safe backend
import matplotlib.pyplot as plt
import seaborn as sns

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    EarlyStoppingCallback,
    TrainerCallback,
    DataCollatorWithPadding,
)

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    roc_curve, auc, confusion_matrix, classification_report,
    f1_score, accuracy_score, matthews_corrcoef,
    average_precision_score, roc_auc_score, balanced_accuracy_score,
)
from sklearn.preprocessing import label_binarize


# ================================================================
# 0. REPRODUCIBILITY & ENVIRONMENT
# ================================================================

def set_seed(seed):
    """Set ALL random seeds for full reproducibility (single seed)."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    # Deterministic algorithms for reproducibility
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def get_environment_info():
    return {
        "python": sys.version.split()[0],
        "torch": torch.__version__,
        "transformers": transformers.__version__,
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "sklearn": sklearn.__version__,
        "cuda_available": torch.cuda.is_available(),
        "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU",
        "gpu_memory_gb": round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2) if torch.cuda.is_available() else "N/A",
        "cuda_version": torch.version.cuda if torch.cuda.is_available() else "N/A",
        "precision_mode": "bf16" if (torch.cuda.is_available() and torch.cuda.is_bf16_supported()) else "fp16",
    }


def _clear_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()


def _log(msg=""):
    """Print with flush to avoid silent-hang appearance in notebooks."""
    print(msg, flush=True)


# ================================================================
# 1. DATA CLEANING / MAPPING / STRATIFIED SPLIT
# ================================================================

def prepare_dataset(df, text_col="input_text", label_col="sentiment_raw",
                    seed=42, test_size=0.1):
    _log("\n" + "=" * 80)
    _log("  DATA PREPARATION")
    _log("=" * 80)

    initial = len(df)
    df = df.dropna(subset=[text_col]).drop_duplicates(subset=[text_col]).reset_index(drop=True)
    _log(f"  Rows after cleaning: {len(df)} (removed {initial - len(df)})")

    if "label" not in df.columns or df["label"].dtype == object:
        df["label"] = df[label_col].map(SENT_MAP)
        df = df.dropna(subset=["label"]).reset_index(drop=True)
        df["label"] = df["label"].astype(int)

    train_val_df, test_df = train_test_split(
        df, test_size=test_size, stratify=df["label"], random_state=seed,
    )
    train_df, val_df = train_test_split(
        train_val_df, test_size=(test_size / (1.0 - test_size)),
        stratify=train_val_df["label"], random_state=seed,
    )

    train_df = train_df.reset_index(drop=True)
    val_df   = val_df.reset_index(drop=True)
    test_df  = test_df.reset_index(drop=True)

    _log(f"\n  Train : {len(train_df)} rows")
    _log(f"  Val   : {len(val_df)} rows")
    _log(f"  Test  : {len(test_df)} rows")
    _log(f"\n  Train dist: {train_df['label'].value_counts().to_dict()}")
    _log(f"  Val   dist: {val_df['label'].value_counts().to_dict()}")
    _log(f"  Test  dist: {test_df['label'].value_counts().to_dict()}")

    classes = np.unique(train_df["label"].to_numpy())
    cw = compute_class_weight(class_weight="balanced", classes=classes,
                              y=train_df["label"].to_numpy())
    class_weights = torch.tensor(cw, dtype=torch.float)
    _log(f"\n  ⚖️ Class weights: {class_weights.numpy().round(4)}")

    return train_df, val_df, test_df, class_weights


# ================================================================
# 2. STRICT DATA VALIDATION
# ================================================================

def validate_data(train_df, val_df, test_df, text_col="input_text", strict=True):
    report = {}
    report["missing"] = {
        s: int(df[text_col].isna().sum())
        for s, df in zip(["train", "val", "test"], [train_df, val_df, test_df])
    }
    report["duplicates"] = {}
    report["duplicate_label_conflicts"] = {}
    for s, df in zip(["train", "val", "test"], [train_df, val_df, test_df]):
        dup_mask = df.duplicated(subset=[text_col], keep=False)
        dup_df = df[dup_mask].copy()
        report["duplicates"][s] = int(len(dup_df))
        if dup_df.empty:
            report["duplicate_label_conflicts"][s] = 0
            continue
        conflicting = dup_df.groupby(text_col)["label"].nunique()
        report["duplicate_label_conflicts"][s] = int((conflicting > 1).sum())

    report["label_conflicts"] = {}
    for s, df in zip(["train", "val", "test"], [train_df, val_df, test_df]):
        lc = df.groupby(text_col)["label"].nunique()
        report["label_conflicts"][s] = int((lc > 1).sum())

    sets = {s: set(df[text_col].astype(str))
            for s, df in zip(["train", "val", "test"], [train_df, val_df, test_df])}
    report["leakage"] = {
        "train_val": len(sets["train"] & sets["val"]),
        "train_test": len(sets["train"] & sets["test"]),
        "val_test": len(sets["val"] & sets["test"]),
    }
    report["class_distribution"] = {
        s: df["label"].value_counts().to_dict()
        for s, df in zip(["train", "val", "test"], [train_df, val_df, test_df])
    }

    if strict:
        if any(v > 0 for v in report["missing"].values()):
            raise ValueError(f"❌ Missing values: {report['missing']}")
        if any(v > 0 for v in report["duplicate_label_conflicts"].values()):
            raise ValueError(f"❌ Duplicate label conflicts: {report['duplicate_label_conflicts']}")
        if any(v > 0 for v in report["leakage"].values()):
            raise ValueError(f"❌ Cross-split leakage: {report['leakage']}")
        if any(v > 0 for v in report["label_conflicts"].values()):
            raise ValueError(f"❌ Label conflicts: {report['label_conflicts']}")
    return report


# ================================================================
# 3. TOKEN LENGTH ANALYSIS (SAMPLED FOR SPEED)
# ================================================================

def analyze_token_lengths(texts, tokenizer, current_max_len, sample_size=5000):
    texts = list(texts)
    sampled = False
    if sample_size and len(texts) > sample_size:
        idx = np.random.RandomState(42).choice(len(texts), sample_size, replace=False)
        texts = [texts[i] for i in idx]
        sampled = True

    lengths = [len(tokenizer.encode(str(x), add_special_tokens=True)) for x in texts]
    truncation_rate = float(np.mean(np.array(lengths) > current_max_len) * 100)

    _log("\n  [Token Length Distribution]" + (f"  (sampled {len(texts)})" if sampled else ""))
    for p in [90, 95, 97, 98, 99, 99.5, 100]:
        _log(f"    {p:>5.1f}% → {np.percentile(lengths, p):.0f} tokens")
    _log(f"    Current MAX_LEN = {current_max_len}")
    _log(f"    Truncation Rate = {truncation_rate:.2f}%")
    return lengths, truncation_rate


# ================================================================
# 4. PAIRED BOOTSTRAP CI
# ================================================================

def compute_bootstrap(y_true, y_pred, target_names, n_bootstrap=1000, ci=0.95, seed=42):
    n = len(y_true)
    rng = np.random.RandomState(seed)
    acc_s, mac_s, wei_s, mcc_s, bal_s = [], [], [], [], []
    pc_f1_s = {cls: [] for cls in target_names}

    for _ in range(n_bootstrap):
        idx = rng.randint(0, n, n)
        yt, yp = y_true[idx], y_pred[idx]
        acc_s.append(accuracy_score(yt, yp))
        mac_s.append(f1_score(yt, yp, average="macro", zero_division=0))
        wei_s.append(f1_score(yt, yp, average="weighted", zero_division=0))
        mcc_s.append(matthews_corrcoef(yt, yp))
        bal_s.append(balanced_accuracy_score(yt, yp))
        pc = f1_score(yt, yp, average=None, labels=list(range(len(target_names))), zero_division=0)
        for i, cls in enumerate(target_names):
            pc_f1_s[cls].append(pc[i])

    def get_ci(scores):
        s = np.array(scores)
        return (float(np.mean(s)),
                float(np.percentile(s, (1 - ci) / 2 * 100)),
                float(np.percentile(s, (1 + ci) / 2 * 100)))

    return {
        "accuracy": get_ci(acc_s), "macro_f1": get_ci(mac_s),
        "weighted_f1": get_ci(wei_s), "mcc": get_ci(mcc_s),
        "balanced_accuracy": get_ci(bal_s),
        "per_class_f1": {cls: get_ci(scores) for cls, scores in pc_f1_s.items()},
    }


# ================================================================
# 5. CALIBRATION & ECE
# ================================================================

def compute_ece_and_plot(y_true, y_probs, target_names, save_path, n_bins=10):
    fig, axes = plt.subplots(1, len(target_names), figsize=(5 * len(target_names), 5))
    if len(target_names) == 1:
        axes = [axes]
    bin_edges = np.linspace(0.0, 1.0, n_bins + 1)
    ece_scores = {}

    for i, cls in enumerate(target_names):
        y_bin = (y_true == i).astype(int)
        prob_pos = y_probs[:, i]
        if y_bin.sum() == 0:
            axes[i].text(0.5, 0.5, "Not in test set", ha="center", va="center")
            ece_scores[cls] = None
            continue
        ece, bin_accs, bin_confs = 0.0, [], []
        for b in range(n_bins):
            lo, hi = bin_edges[b], bin_edges[b + 1]
            mask = (prob_pos >= lo) & (prob_pos <= hi if b == n_bins - 1 else prob_pos < hi)
            count = mask.sum()
            if count > 0:
                acc, conf = float(y_bin[mask].mean()), float(prob_pos[mask].mean())
                ece += (count / len(y_bin)) * abs(acc - conf)
                bin_accs.append(acc)
                bin_confs.append(conf)
            else:
                bin_accs.append(np.nan)
                bin_confs.append(np.nan)
        ece_scores[cls] = float(ece)
        valid = ~np.isnan(bin_accs)
        axes[i].plot(np.array(bin_confs)[valid], np.array(bin_accs)[valid], "s-", label=cls)
        axes[i].plot([0, 1], [0, 1], "k--", label="Perfect")
        axes[i].set_title(f"{cls}\nECE = {ece:.4f}")
        axes[i].set_xlabel("Confidence")
        axes[i].set_ylabel("Accuracy")
        axes[i].set_xlim(0, 1)
        axes[i].set_ylim(0, 1)
        axes[i].grid(True, alpha=0.5)

    plt.suptitle("Probability Calibration (TEST SET)", fontsize=13, y=1.02)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()

    valid_ece = [v for v in ece_scores.values() if v is not None]
    mean_class_ece = float(np.mean(valid_ece)) if valid_ece else None
    return ece_scores, mean_class_ece


# ================================================================
# 6. LABEL PREPARATION
# ================================================================

def _prepare_labels(label_series: pd.Series) -> list:
    if pd.api.types.is_numeric_dtype(label_series):
        return label_series.astype(int).tolist()
    try:
        return label_series.astype(int).tolist()
    except Exception:
        return label_series.map(SENT_MAP).astype(int).tolist()


# ================================================================
# 7. EPOCH METRICS PRINTER CALLBACK
# ================================================================

class EpochMetricsPrinter(TrainerCallback):
    """Prints epoch-level metrics in old-style format."""

    def __init__(self):
        self.last_train_loss = None

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs is None:
            return
        if "loss" in logs and "eval_loss" not in logs:
            self.last_train_loss = float(logs["loss"])

    def on_evaluate(self, args, state, control, metrics=None, **kwargs):
        if metrics is None or state.epoch is None:
            return
        epoch = int(round(state.epoch))
        total_epochs = int(args.num_train_epochs)
        _log("\n" + "=" * 62)
        _log(f"  📊 EPOCH {epoch}/{total_epochs}")
        _log("=" * 62)
        if self.last_train_loss is not None:
            _log(f"  Train Loss          : {self.last_train_loss:.6f}")
        else:
            _log("  Train Loss          : N/A")
        val_loss = metrics.get("eval_loss")
        val_acc  = metrics.get("eval_accuracy")
        val_f1   = metrics.get("eval_macro_f1")
        if val_loss is not None:
            _log(f"  Validation Loss     : {val_loss:.6f}")
        if val_acc is not None:
            _log(f"  Validation Accuracy : {val_acc:.6f}")
        if val_f1 is not None:
            _log(f"  Validation Macro-F1 : {val_f1:.6f}")
        _log("=" * 62 + "\n")


# ================================================================
# 8. LLRD + WEIGHTED TRAINER
# ================================================================

class LLRDWeightedTrainer(WeightedTrainer):
    def __init__(self, *args, use_llrd=False, layer_decay=0.9, **kwargs):
        self.use_llrd = use_llrd
        self.layer_decay = layer_decay
        super().__init__(*args, **kwargs)

    def _reset_optimizer_and_scheduler(self):
        self.optimizer = None
        self.lr_scheduler = None

    def _hp_search_setup(self, trial):
        self._reset_optimizer_and_scheduler()
        try:
            super()._hp_search_setup(trial)
        except AttributeError:
            params = self.hp_space(trial)
            for key, value in params.items():
                setattr(self.args, key, value)

    def train(self, *args, **kwargs):
        trial = kwargs.get("trial", None)
        if trial is None and len(args) >= 2:
            trial = args[1]
        if trial is not None:
            self._reset_optimizer_and_scheduler()
        return super().train(*args, **kwargs)

    def create_optimizer(self):
        if getattr(self, "optimizer", None) is not None:
            return self.optimizer
        if not self.use_llrd:
            optimizer = super().create_optimizer()
            if getattr(self, "optimizer", None) is None:
                self.optimizer = optimizer
            return self.optimizer
        grouped_params = get_optimizer_params(
            self.model, self.args.learning_rate,
            self.args.weight_decay, layer_decay=self.layer_decay,
        )
        self.optimizer = torch.optim.AdamW(
            grouped_params,
            lr=self.args.learning_rate,
            weight_decay=self.args.weight_decay,
        )
        return self.optimizer


# ================================================================
# 9. MAIN PIPELINE v6.1 (SPEED-OPTIMIZED, SINGLE SEED)
# ================================================================

def run_pipeline_v6(config: dict, train_df: pd.DataFrame, val_df: pd.DataFrame,
                    test_df: pd.DataFrame, class_weights: torch.Tensor,
                    report_to: str = "none", n_trials: int = 5) -> dict:

    # 🔴 SINGLE SEED — set once, used everywhere
    set_seed(SEED)

    # ── READ CONFIG ──
    key        = config["key"]
    label      = config["label"]
    checkpoint = config["checkpoint"]
    save_dir   = config["save_dir"]
    output_dir = config["output_dir"]
    tok_dir    = config["tok_dir"]

    use_llrd         = config.get("use_llrd", False)
    layer_decay      = config.get("layer_decay", 0.9)
    use_optuna       = config.get("use_optuna", False)
    use_custom_model = config.get("use_custom_model", False)
    search_epochs    = config.get("search_epochs", 4)
    default_warmup   = config.get("warmup_ratio", 0.1)
    batch_candidates = config.get("batch_size_candidates", [16, 32])
    wd_min, wd_max   = config.get("weight_decay_range", (0.01, 0.20))
    save_total_limit = config.get("save_total_limit", 1)  # 🔴 SPEED: reduced from 2

    # 🔴 SPEED CONFIG
    grad_checkpointing  = config.get("gradient_checkpointing", False)  # OFF by default
    train_diag_size     = config.get("train_diagnostic_size", 1000)    # subset for diagnostics
    num_workers         = config.get("num_workers", 0)                 # avoid deadlock
    batch_train         = config.get("batch_size", BATCH_TRAIN)
    grad_accum          = config.get("grad_accum", GRAD_ACCUM)

    # ── DIRECTORIES ──
    plots_dir = os.path.join(save_dir, "plots")
    model_dir = os.path.join(save_dir, "model")
    for d in [save_dir, tok_dir, output_dir, plots_dir, model_dir]:
        os.makedirs(d, exist_ok=True)

    if os.path.abspath(save_dir) == os.path.abspath(output_dir):
        raise ValueError("save_dir and output_dir must be different.")

    _log("\n" + "=" * 80)
    _log(f"  PIPELINE v6.1 (SPEED-OPTIMIZED): {label}")
    _log("=" * 80)
    _log(f"  Seed            : {SEED} (single)")
    _log(f"  Optuna          : {use_optuna}")
    _log(f"  LLRD            : {use_llrd}")
    _log(f"  Grad Ckpt       : {grad_checkpointing}")
    _log(f"  Batch/Accum     : {batch_train}/{grad_accum}")
    _log(f"  Learning Rate   : {config.get('learning_rate', LR)}")

    # ============================================================
    # STEP 1: STRICT QA
    # ============================================================
    _log("\n[1] Strict Data QA")
    data_report = validate_data(train_df, val_df, test_df, strict=True)
    _log("  ✅ Passed strict QA")

    # ============================================================
    # STEP 2: TOKENIZATION
    # ============================================================
    _log("\n[2] Tokenization & Length Analysis")
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    _, truncation_rate = analyze_token_lengths(
        train_df["input_text"], tokenizer, MAX_LEN, sample_size=5000,
    )

    # 🔴 Dynamic padding: padding=False here, DataCollator pads per-batch
    train_enc = tokenizer(train_df["input_text"].astype(str).tolist(),
                          truncation=True, padding=False, max_length=MAX_LEN)
    val_enc   = tokenizer(val_df["input_text"].astype(str).tolist(),
                          truncation=True, padding=False, max_length=MAX_LEN)
    test_enc  = tokenizer(test_df["input_text"].astype(str).tolist(),
                          truncation=True, padding=False, max_length=MAX_LEN)

    train_labels = _prepare_labels(train_df["label"])
    val_labels   = _prepare_labels(val_df["label"])
    test_labels  = _prepare_labels(test_df["label"])

    train_ds = SentimentDataset(train_enc, train_labels)
    val_ds   = SentimentDataset(val_enc, val_labels)
    test_ds  = SentimentDataset(test_enc, test_labels)

    labels       = list(range(N_LABELS))
    target_names = [str(ID2LABEL[i]) for i in sorted(ID2LABEL.keys())]
    _log(f"  Train: {len(train_ds)} | Val: {len(val_ds)} | Test: {len(test_ds)}")

    # ── MODEL INIT ──
    def model_init(trial=None):
        if use_custom_model:
            return CustomSentimentModel(checkpoint, N_LABELS, ID2LABEL, SENT_MAP)
        return AutoModelForSequenceClassification.from_pretrained(
            checkpoint, num_labels=N_LABELS, id2label=ID2LABEL, label2id=SENT_MAP,
        )

    # ── Dynamic padding collator ──
    data_collator = DataCollatorWithPadding(
        tokenizer=tokenizer, padding=True, pad_to_multiple_of=8,
    )

    # ============================================================
    # STEP 3: OPTUNA PHASE 1 (optional)
    # ============================================================
    best_hparams = {}
    best_objective = None

    if use_optuna:
        _log("\n" + "-" * 80)
        _log("  PHASE 1: OPTUNA SEARCH (Train + Val only)")
        _log("-" * 80)

        search_args = TrainingArguments(
            output_dir=output_dir,
            optim="adamw_torch",
            num_train_epochs=search_epochs,
            per_device_train_batch_size=batch_train,
            per_device_eval_batch_size=BATCH_EVAL,
            learning_rate=config.get("learning_rate", LR),
            weight_decay=WEIGHT_DECAY,
            warmup_ratio=default_warmup,
            gradient_accumulation_steps=grad_accum,
            seed=SEED,
            eval_strategy="epoch",
            save_strategy="no",              # 🔴 SPEED: no checkpoints during search
            load_best_model_at_end=False,
            gradient_checkpointing=grad_checkpointing,
            logging_strategy="epoch",
            logging_steps=10,
            disable_tqdm=True,
            report_to="none",
            tf32=torch.cuda.is_available(),
            dataloader_pin_memory=True,
            dataloader_num_workers=num_workers,
            **get_precision_kwargs(),
        )

        search_trainer = LLRDWeightedTrainer(
            model_init=model_init, args=search_args,
            train_dataset=train_ds, eval_dataset=val_ds,
            compute_metrics=compute_metrics, class_weights=class_weights,
            data_collator=data_collator, use_llrd=use_llrd, layer_decay=layer_decay,
            callbacks=[EpochMetricsPrinter()],
        )

        def hp_space(trial):
            return {
                "learning_rate": trial.suggest_float("learning_rate", 1e-6, 5e-5, log=True),
                "weight_decay": trial.suggest_float("weight_decay", wd_min, wd_max),
                "warmup_ratio": trial.suggest_float("warmup_ratio", 0.05, 0.20),
                "per_device_train_batch_size": trial.suggest_categorical(
                    "per_device_train_batch_size", batch_candidates),
            }

        try:
            best_run = search_trainer.hyperparameter_search(
                direction="maximize", backend="optuna", hp_space=hp_space,
                n_trials=n_trials, compute_objective=lambda m: m["eval_macro_f1"],
                sampler=optuna.samplers.TPESampler(seed=SEED),
            )
        except TypeError:
            best_run = search_trainer.hyperparameter_search(
                direction="maximize", backend="optuna", hp_space=hp_space,
                n_trials=n_trials, compute_objective=lambda m: m["eval_macro_f1"],
            )

        best_hparams   = dict(best_run.hyperparameters)
        best_objective = best_run.objective
        _log(f"\n  BEST OPTUNA Macro-F1: {best_objective:.4f}")
        for k, v in best_hparams.items():
            _log(f"    {k:<35}: {v}")

        del search_trainer
        _clear_memory()

    else:
        _log("\n  Optuna disabled → Using fixed hyperparameters.")
        best_hparams = {
            "learning_rate": config.get("learning_rate", LR),
            "weight_decay": config.get("weight_decay", WEIGHT_DECAY),
            "warmup_ratio": config.get("warmup_ratio", default_warmup),
            "per_device_train_batch_size": config.get("batch_size", BATCH_TRAIN),
        }
        for k, v in best_hparams.items():
            _log(f"    {k:<35}: {v}")

    # ============================================================
    # STEP 4: FINAL TRAINING (SINGLE SEED)
    # ============================================================
    _log("\n" + "-" * 80)
    _log("  PHASE 2: FINAL TRAINING (single seed)")
    _log("-" * 80)

    final_args = TrainingArguments(
        output_dir=output_dir,
        optim="adamw_torch",
        num_train_epochs=EPOCHS,
        per_device_train_batch_size=best_hparams.get("per_device_train_batch_size", batch_train),
        per_device_eval_batch_size=BATCH_EVAL,
        learning_rate=best_hparams.get("learning_rate", LR),
        weight_decay=best_hparams.get("weight_decay", WEIGHT_DECAY),
        warmup_ratio=best_hparams.get("warmup_ratio", default_warmup),
        gradient_accumulation_steps=grad_accum,
        seed=SEED,                          # 🔴 SINGLE SEED
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=save_total_limit,  # 🔴 SPEED: 1 checkpoint max
        save_only_model=True,               # 🔴 SPEED: skip optimizer/scheduler state
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        greater_is_better=True,
        logging_strategy="steps",           # 🔴 SPEED: visible progress
        logging_steps=25,
        logging_first_step=True,
        disable_tqdm=False,
        gradient_checkpointing=grad_checkpointing,  # 🔴 SPEED: OFF by default
        report_to=report_to,
        tf32=torch.cuda.is_available(),
        dataloader_pin_memory=True,
        dataloader_num_workers=num_workers,  # 🔴 SPEED: 0 avoids deadlock
        **get_precision_kwargs(),
    )

    final_trainer = LLRDWeightedTrainer(
        model_init=model_init, args=final_args,
        train_dataset=train_ds, eval_dataset=val_ds,
        compute_metrics=compute_metrics, class_weights=class_weights,
        data_collator=data_collator, use_llrd=use_llrd, layer_decay=layer_decay,
        callbacks=[
            EpochMetricsPrinter(),
            EarlyStoppingCallback(early_stopping_patience=EARLY_STOP_PATIENCE),
        ],
    )

    final_trainer.train()
    _log("\n  ✅ Training complete. Best checkpoint loaded.")

    # ── BEST CHECKPOINT INFO ──
    best_epoch      = getattr(final_trainer.state, "best_epoch", None)
    best_metric     = getattr(final_trainer.state, "best_metric", None)
    best_checkpoint = getattr(final_trainer.state, "best_model_checkpoint", None)
    global_step     = getattr(final_trainer.state, "global_step", None)

    # ============================================================
    # STEP 5: TRAIN vs VAL DIAGNOSTICS (SUBSET FOR SPEED)
    # ============================================================
    _log("\n[Train vs Validation Diagnostics]")

    # 🔴 SPEED: Evaluate only a SUBSET of training data
    train_diag_size = min(train_diag_size, len(train_ds))
    train_diag_ds = torch.utils.data.Subset(train_ds, list(range(train_diag_size)))

    tr_m = final_trainer.evaluate(train_diag_ds, metric_key_prefix="train")
    vl_m = final_trainer.evaluate(val_ds, metric_key_prefix="val")

    tr_f1 = tr_m.get("train_macro_f1", 0)
    vl_f1 = vl_m.get("val_macro_f1", 0)
    train_val_gap = tr_f1 - vl_f1

    if train_val_gap > 0.05:
        gap_status = "⚠️ Potential overfitting (Gap > 0.05)"
    elif train_val_gap < -0.01:
        gap_status = "⚠️ Potential underfitting (Gap < -0.01)"
    else:
        gap_status = "✅ Healthy generalization"

    _log(f"  Train Macro-F1 ({train_diag_size} samples): {tr_f1:.4f}")
    _log(f"  Val   Macro-F1 : {vl_f1:.4f}")
    _log(f"  Gap            : {train_val_gap:+.4f}")
    _log(f"  Status         : {gap_status}")

    # ============================================================
    # STEP 6: INDEPENDENT TEST EVALUATION
    # ============================================================
    _log("\n" + "-" * 80)
    _log("  INDEPENDENT TEST EVALUATION")
    _log("-" * 80)

    test_pred = final_trainer.predict(test_ds)
    logits = test_pred.predictions
    if isinstance(logits, tuple):
        logits = logits[0]
    logits = np.asarray(logits, dtype=np.float32)
    y_true = np.asarray(test_pred.label_ids, dtype=np.int64)

    if N_LABELS == 2 and logits.ndim == 2 and logits.shape[1] == 1:
        prob_pos = torch.sigmoid(torch.tensor(logits[:, 0])).numpy()
        y_probs = np.column_stack([1 - prob_pos, prob_pos])
        y_pred  = (prob_pos >= 0.5).astype(int)
    elif N_LABELS == 2 and logits.ndim == 1:
        prob_pos = torch.sigmoid(torch.tensor(logits)).numpy()
        y_probs = np.column_stack([1 - prob_pos, prob_pos])
        y_pred  = (prob_pos >= 0.5).astype(int)
    else:
        y_pred  = np.argmax(logits, axis=-1)
        y_probs = torch.softmax(torch.tensor(logits, dtype=torch.float32), dim=-1).numpy()

    # ── METRICS ──
    report = classification_report(
        y_true, y_pred, labels=labels, target_names=target_names,
        output_dict=True, zero_division=0,
    )
    report_df = pd.DataFrame(report).transpose()
    per_class_f1 = {
        cls: float(report[cls]["f1-score"]) if cls in report else 0.0
        for cls in target_names
    }

    mcc          = matthews_corrcoef(y_true, y_pred)
    balanced_acc = balanced_accuracy_score(y_true, y_pred)
    test_f1      = f1_score(y_true, y_pred, average="macro", zero_division=0)
    val_test_gap = vl_f1 - test_f1

    y_bin = label_binarize(y_true, classes=labels)
    roc_auc, pr_auc = {}, {}
    for i in range(N_LABELS):
        if len(np.unique(y_bin[:, i])) < 2:
            continue
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_probs[:, i])
        roc_auc[target_names[i]] = float(auc(fpr, tpr))
        pr_auc[target_names[i]]  = float(average_precision_score(y_bin[:, i], y_probs[:, i]))

    try:
        macro_roc_auc = roc_auc_score(y_true, y_probs, multi_class="ovr", average="macro")
    except ValueError:
        macro_roc_auc = None

    _log(f"\n  Accuracy          : {report['accuracy']:.4f}")
    _log(f"  Balanced Accuracy : {balanced_acc:.4f}")
    _log(f"  Macro-F1          : {test_f1:.4f}")
    _log(f"  Weighted-F1       : {report['weighted avg']['f1-score']:.4f}")
    _log(f"  MCC               : {mcc:.4f}")
    if macro_roc_auc is not None:
        _log(f"  Macro ROC-AUC     : {macro_roc_auc:.4f}")
    _log(f"  Val→Test Gap      : {val_test_gap:+.4f}")

    # ── BOOTSTRAP CI ──
    _log("\n[Bootstrap CI (n=1000)]")
    boot = compute_bootstrap(y_true, y_pred, target_names)
    for metric, (mean, lo, hi) in boot.items():
        if metric != "per_class_f1":
            _log(f"  {metric:<20}: {mean:.4f} [{lo:.4f}, {hi:.4f}]")

    # ── CALIBRATION ──
    _log("\n[Calibration / ECE]")
    ece_scores, mean_class_ece = compute_ece_and_plot(
        y_true, y_probs, target_names,
        save_path=os.path.join(plots_dir, "calibration_test.png"),
    )
    for cls, ece in ece_scores.items():
        if ece is not None:
            s = "✅" if ece < 0.05 else ("🟠" if ece < 0.10 else "⚠️")
            _log(f"  {cls:<15}: ECE = {ece:.4f} {s}")
    if mean_class_ece is not None:
        _log(f"  Mean Class ECE  : {mean_class_ece:.4f}")

    # ── GENERALIZATION SUMMARY ──
    _log("\n" + "=" * 80)
    _log("  GENERALIZATION ANALYSIS")
    _log("=" * 80)
    _log(f"  Train F1  : {tr_f1:.4f}")
    _log(f"  Val   F1  : {vl_f1:.4f}")
    _log(f"  Test  F1  : {test_f1:.4f}")
    _log(f"  Train→Val : {train_val_gap:+.4f}")
    _log(f"  Val→Test  : {val_test_gap:+.4f}")
    _log(f"  Status    : {gap_status}")

    # ── ERROR ANALYSIS ──
    _log("\n[Error Analysis]")
    lengths = [
        len(tokenizer.encode(str(test_df["input_text"].iloc[i]), add_special_tokens=True))
        for i in range(len(y_true))
    ]
    errors = []
    for i in range(len(y_true)):
        if y_true[i] != y_pred[i]:
            errors.append({
                "text": test_df["input_text"].iloc[i],
                "true": target_names[y_true[i]],
                "pred": target_names[y_pred[i]],
                "confidence": float(y_probs[i, y_pred[i]]),
                "token_length": lengths[i],
            })
    errors_df = pd.DataFrame(errors).sort_values("confidence", ascending=False)
    errors_df.to_csv(os.path.join(save_dir, "error_analysis.csv"), index=False)
    _log(f"  Saved {len(errors_df)} errors → error_analysis.csv")

    # ── VISUALIZATIONS ──
    _log("\n[Saving Plots]")
    history = final_trainer.state.log_history
    hist_df = pd.DataFrame(history)

    # Loss curve
    tl = [l["loss"] for l in history if "loss" in l and "eval_loss" not in l]
    te = [l["epoch"] for l in history if "loss" in l and "eval_loss" not in l]
    vl_loss = [l["eval_loss"] for l in history if "eval_loss" in l]
    ve = [l["epoch"] for l in history if "eval_loss" in l]

    plt.figure(figsize=(10, 5))
    if tl:
        plt.plot(te, tl, marker="o", label="Train Loss")
    if vl_loss:
        plt.plot(ve, vl_loss, marker="o", label="Validation Loss")
    plt.title(f"Loss Curves: {label}")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "loss_curve.png"), dpi=150)
    plt.close()

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    plt.figure(figsize=(7, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=target_names, yticklabels=target_names)
    plt.title(f"Confusion Matrix (TEST): {label}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "confusion_matrix.png"), dpi=150)
    plt.close()

    # ROC curves
    plt.figure(figsize=(8, 6))
    for i in range(N_LABELS):
        if len(np.unique(y_bin[:, i])) < 2:
            continue
        fpr, tpr, _ = roc_curve(y_bin[:, i], y_probs[:, i])
        plt.plot(fpr, tpr, lw=2, label=f"{target_names[i]} (AUC={auc(fpr, tpr):.3f})")
    plt.plot([0, 1], [0, 1], "k--")
    plt.xlabel("FPR")
    plt.ylabel("TPR")
    plt.title(f"ROC Curves (TEST): {label}")
    plt.legend(loc="lower right")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.tight_layout()
    plt.savefig(os.path.join(plots_dir, "roc_test.png"), dpi=150)
    plt.close()

    # ============================================================
    # SAVE ARTIFACTS
    # ============================================================
    _log("\n[Saving Artifacts]")

    if hasattr(final_trainer.model, "backbone") and \
       hasattr(final_trainer.model.backbone, "gradient_checkpointing_disable"):
        final_trainer.model.backbone.gradient_checkpointing_disable()

    for p in final_trainer.model.parameters():
        p.data = p.data.contiguous()

    final_trainer.save_model(model_dir)
    tokenizer.save_pretrained(tok_dir)

    with open(os.path.join(save_dir, "config.json"), "w") as f:
        json.dump(config, f, indent=2, default=str)

    metrics_out = {
        "test_n": len(y_true),
        "class_distributions": data_report["class_distribution"],
        "accuracy": float(report["accuracy"]),
        "balanced_accuracy": float(balanced_acc),
        "macro_f1": float(test_f1),
        "weighted_f1": float(report["weighted avg"]["f1-score"]),
        "mcc": float(mcc),
        "macro_roc_auc": float(macro_roc_auc) if macro_roc_auc is not None else None,
        "mean_class_ece": mean_class_ece,
        "truncation_rate": float(truncation_rate),
        "per_class_f1": per_class_f1,
        "roc_auc": roc_auc,
        "pr_auc": pr_auc,
        "train_f1": float(tr_f1),
        "val_f1": float(vl_f1),
        "test_f1": float(test_f1),
        "train_val_gap": float(train_val_gap),
        "val_test_gap": float(val_test_gap),
        "gap_status": gap_status,
        "best_epoch": best_epoch,
        "best_val_metric": best_metric,
        "best_checkpoint": str(best_checkpoint) if best_checkpoint else None,
        "global_step": global_step,
        "best_hparams": best_hparams,
        "bootstrap_ci": boot,
        "ece_scores": ece_scores,
        "data_validation": {k: v for k, v in data_report.items() if k != "class_distribution"},
        "environment": get_environment_info(),
    }
    with open(os.path.join(save_dir, "metrics.json"), "w") as f:
        json.dump(metrics_out, f, indent=2, default=str)

    report_df.to_csv(os.path.join(save_dir, "classification_report.csv"))
    hist_df.to_csv(os.path.join(save_dir, "training_history.csv"), index=False)

    preds_df = pd.DataFrame({"true_label": y_true, "predicted_label": y_pred})
    for i, cls in enumerate(target_names):
        preds_df[f"prob_{cls}"] = y_probs[:, i]
    preds_df.to_csv(os.path.join(save_dir, "test_predictions.csv"), index=False)

    if best_hparams:
        pd.DataFrame({
            "parameter": list(best_hparams.keys()),
            "value": list(best_hparams.values()),
        }).to_csv(os.path.join(save_dir, "best_hyperparameters.csv"), index=False)

    _log(f"  Model     → {model_dir}")
    _log(f"  Tokenizer → {tok_dir}")
    _log(f"  Plots     → {plots_dir}")

    del final_trainer
    _clear_memory()

    _log("\n" + "=" * 80)
    _log("  PIPELINE v6.1 COMPLETED SUCCESSFULLY")
    _log("=" * 80)

    return {
        "label": label,
        "best_hparams": best_hparams,
        "test_accuracy": float(report["accuracy"]),
        "test_macro_f1": float(test_f1),
        "test_weighted_f1": float(report["weighted avg"]["f1-score"]),
        "balanced_accuracy": float(balanced_acc),
        "mcc": float(mcc),
        "macro_roc_auc": macro_roc_auc,
        "mean_class_ece": mean_class_ece,
        "per_class_f1": per_class_f1,
        "roc_auc": roc_auc,
        "pr_auc": pr_auc,
        "train_f1": float(tr_f1),
        "val_f1": float(vl_f1),
        "train_val_gap": float(train_val_gap),
        "val_test_gap": float(val_test_gap),
        "gap_status": gap_status,
        "bootstrap_ci": boot,
        "ece_scores": ece_scores,
        "classification_report": report_df,
        "history": hist_df,
        "predictions_df": preds_df,
        "errors_df": errors_df,
    }


# ================================================================
# 10. RUNNER
# ================================================================

if "run_history" not in globals():
    run_history = []
if "all_results" not in globals():
    all_results = {}

BASE_CONFIGS = {
    "muril": {"key": "muril", "label": "MuRIL", "checkpoint": "google/muril-base-cased"},
    "xlmr":  {"key": "xlmr",  "label": "XLM-RoBERTa", "checkpoint": "xlm-roberta-base"},
    "mbert": {"key": "mbert", "label": "mBERT", "checkpoint": "bert-base-multilingual-cased"},
}

DEFAULT_HPARAMS = {
    "learning_rate": 1e-5,
    "weight_decay": 0.15,
    "warmup_ratio": 0.1,
    "batch_size": 32,                     # 🔴 SPEED: larger batch
    "grad_accum": 1,                     # 🔴 SPEED: no accumulation needed
    "use_llrd": False,
    "layer_decay": 0,
    "use_custom_model": False,
    "use_optuna": False,
    "search_epochs": 5,
    "batch_size_candidates": [16, 32],
    "weight_decay_range": (0.01, 0.20),
    "save_total_limit": 1,               # 🔴 SPEED
    "gradient_checkpointing": False,     # 🔴 SPEED: OFF by default
    "train_diagnostic_size": 1000,       # 🔴 SPEED: subset for diagnostics
    "num_workers": 0,                    # 🔴 SPEED: avoids deadlock
}


def run_model(model_key, run_name=None, clean_old=True, n_trials=5, **custom_hparams):
    if model_key not in BASE_CONFIGS:
        raise ValueError(f"Unknown '{model_key}'. Available: {list(BASE_CONFIGS.keys())}")

    cfg = BASE_CONFIGS[model_key].copy()
    cfg.update(DEFAULT_HPARAMS)
    cfg.update(custom_hparams)

    if run_name is None:
        run_name = model_key
    cfg["key"] = run_name

    # Output directories
    if model_key == "xlmr":
        cfg["save_dir"]   = os.path.join(MODEL_ROOT, f"xlm-roberta-base_{run_name}")
        cfg["output_dir"] = os.path.join(TRAINING_ROOT, run_name)
        cfg["tok_dir"]    = os.path.join(TOKENIZER_ROOT, f"xlm-roberta-base_{run_name}")
    elif model_key == "mbert":
        cfg["save_dir"]   = os.path.join(MODEL_ROOT, f"mbert_{run_name}")
        cfg["output_dir"] = os.path.join(TRAINING_ROOT, run_name)
        cfg["tok_dir"]    = os.path.join(TOKENIZER_ROOT, f"mbert_{run_name}")
    elif model_key == "muril":
        cfg["save_dir"]   = os.path.join(MODEL_ROOT, f"muril_{run_name}")
        cfg["output_dir"] = os.path.join(TRAINING_ROOT, run_name)
        cfg["tok_dir"]    = os.path.join(TOKENIZER_ROOT, f"muril_{run_name}")
    else:
        raise ValueError(f"Unsupported model_key: {model_key}")

    if clean_old:
        for d in [cfg["save_dir"], cfg["output_dir"], cfg["tok_dir"]]:
            if os.path.exists(d):
                shutil.rmtree(d)

    # Class weights
    global class_weights
    if "class_weights" not in globals():
        if "train_df" not in globals():
            raise ValueError("train_df not defined. Run prepare_dataset() first.")
        classes = np.unique(train_df["label"].astype(int).to_numpy())
        cw = compute_class_weight("balanced", classes=classes,
                                  y=train_df["label"].astype(int).to_numpy())
        class_weights = torch.tensor(cw, dtype=torch.float)
        _log(f"Class weights: {class_weights.numpy().round(4)}")

    _log(f"\n{'#' * 80}")
    _log(f"  RUNNING: {cfg['label']} | Run: {run_name}")
    _log(f"  Model output : {cfg['save_dir']}")
    _log(f"  Checkpoints  : {cfg['output_dir']}")
    _log(f"  Tokenizer    : {cfg['tok_dir']}")
    _log(f"{'#' * 80}")

    result = run_pipeline_v6(
        config=cfg, train_df=train_df, val_df=val_df, test_df=test_df,
        class_weights=class_weights, report_to="none", n_trials=n_trials,
    )

    all_results[run_name] = result

    run_history.append({
        "run_name": run_name,
        "model": model_key,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "learning_rate": cfg["learning_rate"],
        "use_optuna": cfg["use_optuna"],
        "use_llrd": cfg["use_llrd"],
        "val_macro_f1": result.get("val_f1"),
        "test_macro_f1": result["test_macro_f1"],
        "test_accuracy": result["test_accuracy"],
        "mcc": result.get("mcc"),
        "balanced_accuracy": result.get("balanced_accuracy"),
        "mean_class_ece": result.get("mean_class_ece"),
        "gap_status": result.get("gap_status", ""),
    })

    _log(f"\n✅ {run_name} | Val F1: {result.get('val_f1', 0):.4f} "
         f"| Test F1: {result['test_macro_f1']:.4f}")
    return result


# ================================================================
# 11. COMPARISON
# ================================================================

def show_comparison():
    if not run_history:
        _log("No runs completed yet.")
        return None

    df = pd.DataFrame(run_history)
    cols = ["run_name", "model", "learning_rate", "use_optuna", "use_llrd",
            "val_macro_f1", "test_macro_f1", "balanced_accuracy",
            "mean_class_ece", "gap_status"]

    _log("\n" + "=" * 130)
    _log("RUN COMPARISON")
    _log("=" * 130)
    _log(df[cols].to_string(index=False))

    best_idx = df["val_macro_f1"].idxmax()
    best = df.iloc[best_idx]
    _log(f"\n🏆 Best (by Validation): {best['run_name']}")
    _log(f"   Val F1  = {best['val_macro_f1']:.4f}")
    _log(f"   Test F1 = {best['test_macro_f1']:.4f}")
    return df

In [60]:
run_model("muril", run_name="muril23", debug_mode=True)

################################################################################
  RUNNING: MuRIL | Run: muril23

  Model output : D:\Nepali sentiment\models\muril_muril23
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\muril23
  Tokenizer    : D:\Nepali sentiment\tokenizers\muril_muril23
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): MuRIL
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 31 tokens
     95.0% → 39 tokens
     97.0% → 45 tokens
     98.0% → 49 tokens
     99.0% → 55 tokens
     99.5% → 61 tokens
    100.0% → 92 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1e-05
    weight_decay                       : 0.15
    warmup_ratio                       : 0.1
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.392137
  Validation Loss     : 0.362111
  Validation Accuracy : 0.629560
  Validation Macro-F1 : 0.559666
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.295687
  Validation Loss     : 0.282532
  Validation Accuracy : 0.747428
  Validation Macro-F1 : 0.741702
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.260685
  Validation Loss     : 0.242999
  Validation Accuracy : 0.762395
  Validation Macro-F1 : 0.759368
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.201630
  Validation Loss     : 0.226397
  Validation Accuracy : 0.782039
  Validation Macro-F1 : 0.781490
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.181904
  Validation Loss     : 0.221491
  Validation Accuracy : 0.781104
  Validation Macro-F1 : 0.779739
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.181904
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.181904
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8175
  Val   Macro-F1 : 0.7815
  Gap            : +0.0360
  Status         : ✅ Healthy generalization

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.7437
  Balanced Accuracy : 0.7463
  Macro-F1          : 0.7429
  Weighted-F1       : 0.7411
  MCC               : 0.6173
  Macro ROC-AUC     : 0.8814
  Val→Test Gap      : +0.0386

[Bootstrap CI (n=1000)]
  accuracy            : 0.7441 [0.7194, 0.7699]
  macro_f1            : 0.7430 [0.7184, 0.7687]
  weighted_f1         : 0.7416 [0.7161, 0.7679]
  mcc                 : 0.6179 [0.5813, 0.6571]
  balanced_accuracy   : 0.7465 [0.7224, 0.7713]

[Calibration / ECE]
  Positive       : ECE = 0.1266 ⚠️
  Neutral        : ECE = 0.1259 ⚠️
  Negative       : ECE = 0.1330 ⚠️
  Mean Class ECE  : 0.1285

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8175
  Val   F1  : 0.7815
  Test  F1  : 0.7429
  Train→Val : +0.0360
  Val→Test  : +0.0386
  Status    : ✅ Healthy generalization

[Error Analysis]
  Saved 274 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\muril_muril23\model
  Tokenizer → D:\Nepali sentiment\tokenizers\muril_muril23
  Plots     → D:\Nepali sentiment\models\muril_muril23\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ muril23 | Val F1: 0.7815 | Test F1: 0.7429

{'label': 'MuRIL',
 'best_hparams': {'learning_rate': 1e-05,
  'weight_decay': 0.15,
  'warmup_ratio': 0.1,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.7436856875584659,
 'test_macro_f1': 0.7429234276850721,
 'test_weighted_f1': 0.7411040711296863,
 'balanced_accuracy': 0.7462703201508466,
 'mcc': 0.6173152294309686,
 'macro_roc_auc': np.float64(0.8814033159082125),
 'mean_class_ece': 0.1285085816564759,
 'per_class_f1': {'Positive': 0.841248303934871,
  'Neutral': 0.6481994459833795,
  'Negative': 0.7393225331369662},
 'roc_auc': {'Positive': 0.9461245896388822,
  'Neutral': 0.8004942403486924,
  'Negative': 0.897591117737063},
 'pr_auc': {'Positive': 0.9029588000793638,
  'Neutral': 0.6546832157068747,
  'Negative': 0.8247928400490386},
 'train_f1': 0.8174797048880992,
 'val_f1': 0.7814899640471841,
 'train_val_gap': 0.03598974084091511,
 'val_test_gap': 0.038566536362111936,
 'gap_status': '✅ Healthy generalization',
 'bootstrap_ci': {'accuracy': (0.7441028999064547,
   0.7193638914873713,
   0.7699017773620206),
  'macro_f1': (0.742991795736931, 0.7183674251994643, 0.7687069578450678),
  'weighted_f1': (0.7415589675257082, 0.7160569805832235, 0.7679098795088262),
  'mcc': (0.6178742065712524, 0.5812641227056781, 0.6570874690137771),
  'balanced_accuracy': (0.7464877586378261,
   0.722431055744821,
   0.771280085556434),
  'per_class_f1': {'Positive': (0.841815064505354,
    0.8141818999100988,
    0.8692451523545707),
   'Neutral': (0.6478779608520784, 0.606611677456952, 0.6883581283945619),
   'Negative': (0.7392823618533608, 0.7024539877300614, 0.7755742575087154)}},
 'ece_scores': {'Positive': 0.12662427125967363,
  'Neutral': 0.12586458424634195,
  'Negative': 0.1330368894634122},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.790816  0.898551  0.841248   345.000000
 Neutral        0.655462  0.641096  0.648199   365.000000
 Negative       0.784375  0.699164  0.739323   359.000000
 accuracy       0.743686  0.743686  0.743686     0.743686
 macro avg      0.743551  0.746270  0.742923  1069.000000
 weighted avg   0.742438  0.743686  0.741104  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.487934   0.253372   0.000000e+00  0.003731     1        NaN
 1   0.488113   0.175614   1.791045e-06  0.093284    25        NaN
 2   0.488383   0.055276   3.656716e-06  0.186567    50        NaN
 3   0.488105   0.041387   5.522388e-06  0.279851    75        NaN
 4   0.487766   0.113685   7.388060e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 57  0.181904   3.514154   1.326700e-07  4.944030  1325        NaN
 58       NaN        NaN            NaN  5.000000  1340   0.221491
 59       NaN        NaN            NaN  5.000000  1340        NaN
 60       NaN        NaN            NaN  5.000000  1340        NaN
 61       NaN        NaN            NaN  5.000000  1340        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 57            NaN            NaN            NaN               NaN  ...
 58       0.781104       0.779739       0.781104          0.778381  ...
 59            NaN            NaN            NaN               NaN  ...
 60            NaN            NaN            NaN               NaN  ...
 61            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 57             NaN                NaN       NaN           NaN           NaN
 58             NaN                NaN       NaN           NaN           NaN
 59             NaN                NaN       NaN           NaN           NaN
 60           0.818           0.814937       NaN           NaN           NaN
 61             NaN                NaN  0.226397      0.782039       0.78149

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 57           NaN              NaN          NaN                     NaN
 58           NaN              NaN          NaN                     NaN
 59           NaN              NaN          NaN                     NaN
 60           NaN              NaN          NaN                     NaN
 61      0.782039         0.780234       1.8872                 566.456

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 57                   NaN
 58                   NaN
 59                   NaN
 60                   NaN
 61                18.016

 [62 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                0       0.666889      0.207807       0.125305
 1              0                0       0.661752      0.216313       0.121935
 2              0                0       0.664446      0.212162       0.123391
 3              1                1       0.176710      0.507347       0.315943
 4              2                1       0.197848      0.511177       0.290976
 ...          ...              ...            ...           ...            ...
 1064           2                1       0.157346      0.507921       0.334733
 1065           0                0       0.446970      0.387955       0.165075
 1066           0                0       0.667747      0.201279       0.130975
 1067           1                0       0.603119      0.269468       0.127412
 1068           1                1       0.157452      0.506280       0.336268

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 65   अमर दाई अमृत दाई र दुर्गा दिदी सधैँ उत्कृष्ट ह...   Neutral  Positive
 64                           एक दम माया लागो बाबु को 😢   Neutral  Positive
 87                   मनिष बुबा निकै रमाइलो हुनुहुन्छ 😂   Neutral  Positive
 109   मेरो एकमात्र मनपर्ने गुलशन दाई भारतबाट धेरै माया   Neutral  Positive
 121                                    वाह सलाम छ छोरी  Negative  Positive
 ..                                                 ...       ...       ...
 99   धत्तेरिका कडा। हामीलाई उनी जस्तै धेरै मानिसहरू...  Positive   Neutral
 36   राम्रो यसरी नेपालको खाएर... इन्डियाको गुन गाउन...  Negative   Neutral
 92                          कति समझदार छ निषेध र बहिनी  Positive   Neutral
 146  कति ल्याङ ल्याङ गरेको हो हामी यहाँ जापानमा हिन...  Negative   Neutral
 77   म्यादी प्रहरी हेर्दा मात्र हुन्छ उनीसँग के त्य...  Negative  Positive

      confidence  token_length
 65     0.669187            14
 64     0.668855            10
 87     0.668447             9
 109    0.668217            10
 121    0.667722             6
 ..          ...           ...
 99     0.426833            16
 36     0.426315            21
 92     0.426045             8
 146    0.423335            43
 77     0.421284            15

 [274 rows x 5 columns]}

In [21]:
run_model("mbert", run_name="mbert23", debug_mode=True)

################################################################################
  RUNNING: mBERT | Run: mbert23
  Model output : D:\Nepali sentiment\models\mbert_mbert23
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\mbert23
  Tokenizer    : D:\Nepali sentiment\tokenizers\mbert_mbert23
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): mBERT
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 61 tokens
     95.0% → 77 tokens
     97.0% → 87 tokens
     98.0% → 95 tokens
     99.0% → 107 tokens
     99.5% → 119 tokens
    100.0% → 194 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1e-05
    weight_decay                       : 0.15
    warmup_ratio                       : 0.1
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.337365
  Validation Loss     : 0.321475
  Validation Accuracy : 0.636109
  Validation Macro-F1 : 0.622947
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.244709
  Validation Loss     : 0.229325
  Validation Accuracy : 0.721235
  Validation Macro-F1 : 0.719248
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.217429
  Validation Loss     : 0.228926
  Validation Accuracy : 0.737138
  Validation Macro-F1 : 0.734840
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.171569
  Validation Loss     : 0.231794
  Validation Accuracy : 0.753040
  Validation Macro-F1 : 0.752494
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.128986
  Validation Loss     : 0.251473
  Validation Accuracy : 0.747428
  Validation Macro-F1 : 0.747151
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.128986
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.128986
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8485
  Val   Macro-F1 : 0.7506
  Gap            : +0.0979
  Status         : ⚠️ Potential overfitting (Gap > 0.05)

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.7166
  Balanced Accuracy : 0.7186
  Macro-F1          : 0.7167
  Weighted-F1       : 0.7152
  MCC               : 0.5760
  Macro ROC-AUC     : 0.8788
  Val→Test Gap      : +0.0339

[Bootstrap CI (n=1000)]
  accuracy            : 0.7167 [0.6904, 0.7418]
  macro_f1            : 0.7164 [0.6901, 0.7422]
  weighted_f1         : 0.7153 [0.6887, 0.7413]
  mcc                 : 0.5763 [0.5366, 0.6142]
  balanced_accuracy   : 0.7186 [0.6929, 0.7437]

[Calibration / ECE]
  Positive       : ECE = 0.0592 🟠
  Neutral        : ECE = 0.0756 🟠
  Negative       : ECE = 0.0570 🟠
  Mean Class ECE  : 0.0639

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8485
  Val   F1  : 0.7506
  Test  F1  : 0.7167
  Train→Val : +0.0979
  Val→Test  : +0.0339
  Status    : ⚠️ Potential overfitting (Gap > 0.05)

[Error Analysis]
  Saved 303 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\mbert_mbert23\model
  Tokenizer → D:\Nepali sentiment\tokenizers\mbert_mbert23
  Plots     → D:\Nepali sentiment\models\mbert_mbert23\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ mbert23 | Val F1: 0.7506 | Test F1: 0.7167

{'label': 'mBERT',
 'best_hparams': {'learning_rate': 1e-05,
  'weight_decay': 0.15,
  'warmup_ratio': 0.1,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.7165575304022451,
 'test_macro_f1': 0.7166579050508375,
 'test_weighted_f1': 0.7151532968816229,
 'balanced_accuracy': 0.7185595764969679,
 'mcc': 0.5760229744106129,
 'macro_roc_auc': np.float64(0.8788396213904545),
 'mean_class_ece': 0.06391623358572983,
 'per_class_f1': {'Positive': 0.8,
  'Neutral': 0.6430517711171662,
  'Negative': 0.7069219440353461},
 'roc_auc': {'Positive': 0.9322523820962446,
  'Neutral': 0.8248871419676215,
  'Negative': 0.8793793401074972},
 'pr_auc': {'Positive': 0.8847567671530985,
  'Neutral': 0.6850155080355002,
  'Negative': 0.7970780767653839},
 'train_f1': 0.8485006448018284,
 'val_f1': 0.7505861398209448,
 'train_val_gap': 0.09791450498088361,
 'val_test_gap': 0.03392823477010731,
 'gap_status': '⚠️ Potential overfitting (Gap > 0.05)',
 'bootstrap_ci': {'accuracy': (0.7167184284377923,
   0.6903648269410664,
   0.7418147801683816),
  'macro_f1': (0.7164364589330954, 0.6901492431390261, 0.7422065956385072),
  'weighted_f1': (0.715323893708157, 0.6887105591682137, 0.7413456737589675),
  'mcc': (0.576266346386083, 0.5366104025737606, 0.6142484557049747),
  'balanced_accuracy': (0.7185670049790572,
   0.6929469702596265,
   0.7436928602797183),
  'per_class_f1': {'Positive': (0.8000096061853015,
    0.7665621842134811,
    0.8290745766733776),
   'Neutral': (0.6430979992015985, 0.6028955314009662, 0.6821766465238357),
   'Negative': (0.7062017714123863, 0.6686831350057579, 0.7449913702520561)}},
 'ece_scores': {'Positive': 0.059152729391103824,
  'Neutral': 0.07561491184473261,
  'Negative': 0.05698105952135306},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.763158  0.840580  0.800000   345.000000
 Neutral        0.639566  0.646575  0.643052   365.000000
 Negative       0.750000  0.668524  0.706922   359.000000
 accuracy       0.716558  0.716558  0.716558     0.716558
 macro avg      0.717575  0.718560  0.716658  1069.000000
 weighted avg   0.716540  0.716558  0.715153  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.502285   2.576465   0.000000e+00  0.003731     1        NaN
 1   0.492723   2.371063   1.791045e-06  0.093284    25        NaN
 2   0.489078   5.077172   3.656716e-06  0.186567    50        NaN
 3   0.490249   2.333702   5.522388e-06  0.279851    75        NaN
 4   0.484375   2.556867   7.388060e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 57  0.128986   5.776099   1.326700e-07  4.944030  1325        NaN
 58       NaN        NaN            NaN  5.000000  1340   0.251473
 59       NaN        NaN            NaN  5.000000  1340        NaN
 60       NaN        NaN            NaN  5.000000  1340        NaN
 61       NaN        NaN            NaN  5.000000  1340        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 57            NaN            NaN            NaN               NaN  ...
 58       0.747428       0.747151       0.747428          0.745814  ...
 59            NaN            NaN            NaN               NaN  ...
 60            NaN            NaN            NaN               NaN  ...
 61            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 57             NaN                NaN       NaN           NaN           NaN
 58             NaN                NaN       NaN           NaN           NaN
 59             NaN                NaN       NaN           NaN           NaN
 60           0.848           0.846174       NaN           NaN           NaN
 61             NaN                NaN  0.232019      0.751169      0.750586

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 57           NaN              NaN          NaN                     NaN
 58           NaN              NaN          NaN                     NaN
 59           NaN              NaN          NaN                     NaN
 60           NaN              NaN          NaN                     NaN
 61      0.751169         0.749198       1.1252                 950.093

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 57                   NaN
 58                   NaN
 59                   NaN
 60                   NaN
 61                30.218

 [62 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                0       0.760890      0.224042       0.015069
 1              0                0       0.581202      0.393261       0.025536
 2              0                0       0.663600      0.283190       0.053210
 3              1                1       0.145386      0.600261       0.254353
 4              2                1       0.319469      0.508023       0.172509
 ...          ...              ...            ...           ...            ...
 1064           2                1       0.072202      0.648576       0.279222
 1065           0                1       0.164795      0.781599       0.053606
 1066           0                0       0.843590      0.145453       0.010956
 1067           1                0       0.505743      0.475102       0.019156
 1068           1                1       0.013554      0.689777       0.296669

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 41       हजुरको कुरा सुन्दा हाम्रो समय खेर गयो सजित सर  Negative   Neutral
 136                                    वाह सलाम छ छोरी  Negative  Positive
 196                 हहाहाहाहाहाहा म त पागल भएँ कमेडीले  Positive  Negative
 157  बहादुर केटी उनलाई सलाम समीक्षाको लागि बोल्ने त...  Positive  Negative
 81   अमर दाई अमृत दाई र दुर्गा दिदी सधैँ उत्कृष्ट ह...   Neutral  Positive
 ..                                                 ...       ...       ...
 4               यसले अभिनय गर्न जानेन शिशिर दाजु......  Negative  Positive
 200  रहिसा उत्कृष्ट छिन् तर बुद्ध लामाले कहिल्यै बु...  Negative   Neutral
 117  अब सुहाउने गर्छ शङ्करले कहिल्यै आश छैन त्यो त ...   Neutral  Positive
 252           चन्दलाई त्यत्रो मन परेको ...उफ..उफ्फ्फ्फ़  Negative  Positive
 194         कति कति मिथॊऒऒऒओ बोलि हो हजर को मुआ 😍😚😑😚😊☺  Positive  Negative

      confidence  token_length
 41     0.843547            25
 136    0.840479            11
 196    0.837102            20
 157    0.835907            35
 81     0.812400            38
 ..          ...           ...
 4      0.383868            23
 200    0.363722            60
 117    0.357184            50
 252    0.345783            21
 194    0.342321            19

 [303 rows x 5 columns]}

In [23]:
run_model("xlmr", run_name="xlmr23", debug_mode=True)

################################################################################
  RUNNING: XLM-RoBERTa | Run: xlmr23
  Model output : D:\Nepali sentiment\models\xlm-roberta-base_xlmr23
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\xlmr23
  Tokenizer    : D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr23
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): XLM-RoBERTa
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 36 tokens
     95.0% → 46 tokens
     97.0% → 53 tokens
     98.0% → 56 tokens
     99.0% → 63 tokens
     99.5% → 70 tokens
    100.0% → 106 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1e-05
    weight_decay                       : 0.15
    warmup_ratio                       : 0.1
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.321313
  Validation Loss     : 0.267370
  Validation Accuracy : 0.725912
  Validation Macro-F1 : 0.720805
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.234711
  Validation Loss     : 0.214884
  Validation Accuracy : 0.758653
  Validation Macro-F1 : 0.755798
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.232452
  Validation Loss     : 0.202418
  Validation Accuracy : 0.773620
  Validation Macro-F1 : 0.770927
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.174061
  Validation Loss     : 0.209335
  Validation Accuracy : 0.768943
  Validation Macro-F1 : 0.766422
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.165910
  Validation Loss     : 0.209665
  Validation Accuracy : 0.783910
  Validation Macro-F1 : 0.783307
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.165910
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.165910
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8177
  Val   Macro-F1 : 0.7833
  Gap            : +0.0344
  Status         : ✅ Healthy generalization

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.7587
  Balanced Accuracy : 0.7605
  Macro-F1          : 0.7596
  Weighted-F1       : 0.7582
  MCC               : 0.6395
  Macro ROC-AUC     : 0.9071
  Val→Test Gap      : +0.0237

[Bootstrap CI (n=1000)]
  accuracy            : 0.7590 [0.7324, 0.7839]
  macro_f1            : 0.7597 [0.7327, 0.7853]
  weighted_f1         : 0.7586 [0.7311, 0.7839]
  mcc                 : 0.6400 [0.6000, 0.6783]
  balanced_accuracy   : 0.7607 [0.7355, 0.7858]

[Calibration / ECE]
  Positive       : ECE = 0.0448 ✅
  Neutral        : ECE = 0.0732 🟠
  Negative       : ECE = 0.0642 🟠
  Mean Class ECE  : 0.0607

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8177
  Val   F1  : 0.7833
  Test  F1  : 0.7596
  Train→Val : +0.0344
  Val→Test  : +0.0237
  Status    : ✅ Healthy generalization

[Error Analysis]
  Saved 258 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr23\model
  Tokenizer → D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr23
  Plots     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr23\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ xlmr23 | Val F1: 0.7833 | Test F1: 0.7596

{'label': 'XLM-RoBERTa',
 'best_hparams': {'learning_rate': 1e-05,
  'weight_decay': 0.15,
  'warmup_ratio': 0.1,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.7586529466791394,
 'test_macro_f1': 0.7596338824415064,
 'test_weighted_f1': 0.7582006748139527,
 'balanced_accuracy': 0.7604667705958268,
 'mcc': 0.6394573384143248,
 'macro_roc_auc': np.float64(0.9070615256565134),
 'mean_class_ece': 0.06073542840785797,
 'per_class_f1': {'Positive': 0.8361111111111111,
  'Neutral': 0.6827309236947792,
  'Negative': 0.7600596125186289},
 'roc_auc': {'Positive': 0.9540475618544318,
  'Neutral': 0.8523894769613948,
  'Negative': 0.9147475381537135},
 'pr_auc': {'Positive': 0.912042592493664,
  'Neutral': 0.7458357875002548,
  'Negative': 0.8510013108194618},
 'train_f1': 0.8176932792396459,
 'val_f1': 0.7833069844099256,
 'train_val_gap': 0.03438629482972022,
 'val_test_gap': 0.023673101968419208,
 'gap_status': '✅ Healthy generalization',
 'bootstrap_ci': {'accuracy': (0.7590346117867166,
   0.7324368568755847,
   0.7839101964452759),
  'macro_f1': (0.7596662475607675, 0.7327000549383222, 0.7852960761207465),
  'weighted_f1': (0.7585875406891075, 0.7311440429183549, 0.7838584940066344),
  'mcc': (0.6399703643348728, 0.6000397789112921, 0.6782595217112505),
  'balanced_accuracy': (0.7607069378241332,
   0.7354743884131173,
   0.7858398172436912),
  'per_class_f1': {'Positive': (0.8365232256267764,
    0.8049792531120332,
    0.8635200429491767),
   'Neutral': (0.6823125053499361, 0.6421710423299755, 0.7197994858611825),
   'Negative': (0.76016301170559, 0.725018503002374, 0.7959632441667115)}},
 'ece_scores': {'Positive': 0.04475196783053641,
  'Neutral': 0.07320784991371843,
  'Negative': 0.06424646747931907},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.802667  0.872464  0.836111   345.000000
 Neutral        0.667539  0.698630  0.682731   365.000000
 Negative       0.817308  0.710306  0.760060   359.000000
 accuracy       0.758653  0.758653  0.758653     0.758653
 macro avg      0.762505  0.760467  0.759634  1069.000000
 weighted avg   0.761446  0.758653  0.758201  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.557885   5.060678   0.000000e+00  0.003731     1        NaN
 1   0.508159   7.078846   1.791045e-06  0.093284    25        NaN
 2   0.497451   1.794554   3.656716e-06  0.186567    50        NaN
 3   0.495372   1.736448   5.522388e-06  0.279851    75        NaN
 4   0.489132   4.060601   7.388060e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 57  0.165910   9.801698   1.326700e-07  4.944030  1325        NaN
 58       NaN        NaN            NaN  5.000000  1340   0.209665
 59       NaN        NaN            NaN  5.000000  1340        NaN
 60       NaN        NaN            NaN  5.000000  1340        NaN
 61       NaN        NaN            NaN  5.000000  1340        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 57            NaN            NaN            NaN               NaN  ...
 58        0.78391       0.783307        0.78391          0.782006  ...
 59            NaN            NaN            NaN               NaN  ...
 60            NaN            NaN            NaN               NaN  ...
 61            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 57             NaN                NaN       NaN           NaN           NaN
 58             NaN                NaN       NaN           NaN           NaN
 59             NaN                NaN       NaN           NaN           NaN
 60           0.818            0.81504       NaN           NaN           NaN
 61             NaN                NaN  0.209665       0.78391      0.783307

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 57           NaN              NaN          NaN                     NaN
 58           NaN              NaN          NaN                     NaN
 59           NaN              NaN          NaN                     NaN
 60           NaN              NaN          NaN                     NaN
 61       0.78391         0.782006       0.8129                1315.124

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 57                   NaN
 58                   NaN
 59                   NaN
 60                   NaN
 61                41.828

 [62 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                0       0.835462      0.151852       0.012686
 1              0                0       0.729779      0.253192       0.017029
 2              0                0       0.835685      0.154586       0.009729
 3              1                1       0.427509      0.434241       0.138251
 4              2                1       0.184811      0.724191       0.090998
 ...          ...              ...            ...           ...            ...
 1064           2                1       0.015967      0.524641       0.459391
 1065           0                0       0.534946      0.443486       0.021568
 1066           0                0       0.888439      0.102144       0.009418
 1067           1                0       0.543906      0.437041       0.019053
 1068           1                1       0.017754      0.766803       0.215443

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 63   अमर दाई अमृत दाई र दुर्गा दिदी सधैँ उत्कृष्ट ह...   Neutral  Positive
 161           तपाईँले पनि गज्जबको कुरा गर्नुहुन्छ बुढो   Neutral  Positive
 109                                    वाह सलाम छ छोरी  Negative  Positive
 76                             उप-विजेता टोली प्रखर ❣️   Neutral  Positive
 170                    गुलशन बास्तोलाको डान्स राम्रो छ   Neutral  Positive
 ..                                                 ...       ...       ...
 139              भिम रावललाई प्रधानमन्त्री बनाउनु पर्छ  Positive   Neutral
 71   शुभकामना ढकाल जी यो झारपात मिडियाको पछि नलाग्न...  Positive   Neutral
 210  जगदीश सर हजुरको कामलाई सलाम छ। आस्तालाई ठिक पा...  Positive   Neutral
 136  राम्रो नै छन् तर मेरो उत्कृष्ट जुम्ल्याहा दीपा...  Positive   Neutral
 127  बहादुर केटी उनलाई सलाम समीक्षाको लागि बोल्ने त...  Positive  Negative

      confidence  token_length
 63     0.869876            18
 161    0.869817            15
 109    0.868540             6
 76     0.841299            13
 170    0.836205            12
 ..          ...           ...
 139    0.465519            11
 71     0.412985            20
 210    0.408497            35
 136    0.406244            18
 127    0.365060            24

 [258 rows x 5 columns]}

In [ ]:
# Fastest approach: Just use the best HPs directly, no searching
run_model(
    "xlmr",
    run_name="xlmr_fixed_best_hps",
    use_optuna=False,       # Optuna already done → use fixed HPs
    use_llrd=False,
    learning_rate=1.0953e-05,      # from Optuna: 1.0952662748632564e-05
    weight_decay=0.0365,           # from Optuna: 0.036503833523887946
    warmup_ratio=0.0938,           # from Optuna: 0.09382169728028272
    batch_size=32,                 # from Optuna: 32.0
)

################################################################################
  RUNNING: XLM-RoBERTa | Run: xlmr_fixed_best_hps
  Model output : D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\xlmr_fixed_best_hps
  Tokenizer    : D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr_fixed_best_hps
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): XLM-RoBERTa
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1.0953e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 36 tokens
     95.0% → 46 tokens
     97.0% → 53 tokens
     98.0% → 56 tokens
     99.0% → 63 tokens
     99.5% → 70 tokens
    100.0% → 106 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1.0953e-05
    weight_decay                       : 0.0365
    warmup_ratio                       : 0.0938
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/8
==============================================================
  Train Loss          : 0.337471
  Validation Loss     : 0.269061
  Validation Accuracy : 0.704397
  Validation Macro-F1 : 0.701579
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/8
==============================================================
  Train Loss          : 0.245155
  Validation Loss     : 0.209391
  Validation Accuracy : 0.757717
  Validation Macro-F1 : 0.751482
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/8
==============================================================
  Train Loss          : 0.223571
  Validation Loss     : 0.219302
  Validation Accuracy : 0.771749
  Validation Macro-F1 : 0.766039
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.179221
  Validation Loss     : 0.208114
  Validation Accuracy : 0.770814
  Validation Macro-F1 : 0.768641
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/8
==============================================================
  Train Loss          : 0.138776
  Validation Loss     : 0.239812
  Validation Accuracy : 0.778297
  Validation Macro-F1 : 0.776822
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 6/8
==============================================================
  Train Loss          : 0.139979
  Validation Loss     : 0.231493
  Validation Accuracy : 0.785781
  Validation Macro-F1 : 0.783564
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 7/8
==============================================================
  Train Loss          : 0.111155
  Validation Loss     : 0.240392
  Validation Accuracy : 0.793265
  Validation Macro-F1 : 0.793045
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.127502
  Validation Loss     : 0.248330
  Validation Accuracy : 0.787652
  Validation Macro-F1 : 0.787252
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.127502
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.127502
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8794
  Val   Macro-F1 : 0.7930
  Gap            : +0.0863
  Status         : ⚠️ Potential overfitting (Gap > 0.05)

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.5323
  Balanced Accuracy : 0.5311
  Macro-F1          : 0.5240
  Weighted-F1       : 0.5237
  MCC               : 0.3094
  Macro ROC-AUC     : 0.7555
  Val→Test Gap      : +0.2691

[Bootstrap CI (n=1000)]
  accuracy            : 0.5322 [0.5042, 0.5631]
  macro_f1            : 0.5234 [0.4933, 0.5556]
  weighted_f1         : 0.5235 [0.4933, 0.5563]
  mcc                 : 0.3095 [0.2675, 0.3538]
  balanced_accuracy   : 0.5310 [0.5045, 0.5597]

[Calibration / ECE]
  Positive       : ECE = 0.1676 ⚠️
  Neutral        : ECE = 0.0765 🟠
  Negative       : ECE = 0.1339 ⚠️
  Mean Class ECE  : 0.1260

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8794
  Val   F1  : 0.7930
  Test  F1  : 0.5240
  Train→Val : +0.0863
  Val→Test  : +0.2691
  Status    : ⚠️ Potential overfitting (Gap > 0.05)

[Error Analysis]
  Saved 500 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps\model
  Tokenizer → D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr_fixed_best_hps
  Plots     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ xlmr_fixed_best_hps | Val F1: 0.7930 | Test F1: 0.5240

{'label': 'XLM-RoBERTa',
 'best_hparams': {'learning_rate': 1.0953e-05,
  'weight_decay': 0.0365,
  'warmup_ratio': 0.0938,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.5322731524789522,
 'test_macro_f1': 0.523963776817045,
 'test_weighted_f1': 0.5237202622253095,
 'balanced_accuracy': 0.5310612578746,
 'mcc': 0.30940399003347063,
 'macro_roc_auc': np.float64(0.755479838812395),
 'mean_class_ece': 0.12600899875189586,
 'per_class_f1': {'Positive': 0.5067698259187621,
  'Neutral': 0.4573002754820937,
  'Negative': 0.6078212290502794},
 'roc_auc': {'Positive': 0.8002922153199178,
  'Neutral': 0.679313900996264,
  'Negative': 0.7868334001210034},
 'pr_auc': {'Positive': 0.6937117417589627,
  'Neutral': 0.5191097606712296,
  'Negative': 0.6784077140144009},
 'train_f1': 0.8793595546786922,
 'val_f1': 0.7930451695700458,
 'train_val_gap': 0.08631438510864642,
 'val_test_gap': 0.2690813927530008,
 'gap_status': '⚠️ Potential overfitting (Gap > 0.05)',
 'bootstrap_ci': {'accuracy': (0.5322057998129093,
   0.5041861552853134,
   0.5631431244153414),
  'macro_f1': (0.5233777964135689, 0.49334504861130224, 0.5556026576060812),
  'weighted_f1': (0.523495870606017, 0.4932666650515947, 0.5563464345825362),
  'mcc': (0.30946398558242255, 0.26745563326259214, 0.35384381262375325),
  'balanced_accuracy': (0.5310434880693553,
   0.5044641119431535,
   0.5597329039057105),
  'per_class_f1': {'Positive': (0.5056279918186708,
    0.4523684997011357,
    0.5543570549630845),
   'Neutral': (0.45620581734788207, 0.4081470449451457, 0.5013559571528863),
   'Negative': (0.6082995800741535, 0.5700738875105464, 0.6479759162198324)}},
 'ece_scores': {'Positive': 0.1675811836616222,
  'Neutral': 0.07654043398553574,
  'Negative': 0.13390537860852963},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.766082  0.378613  0.506770   346.000000
 Neutral        0.459834  0.454795  0.457300   365.000000
 Negative       0.506518  0.759777  0.607821   358.000000
 accuracy       0.532273  0.532273  0.532273     0.532273
 macro avg      0.577478  0.531061  0.523964  1069.000000
 weighted avg   0.574590  0.532273  0.523720  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.557885   5.060678   0.000000e+00  0.003731     1        NaN
 1   0.508338   1.553794   1.301347e-06  0.093284    25        NaN
 2   0.498725   1.829045   2.656916e-06  0.186567    50        NaN
 3   0.498301   4.942910   4.012485e-06  0.279851    75        NaN
 4   0.494490   3.533077   5.368054e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 92  0.127502   6.417933   1.128012e-07  7.929104  2125        NaN
 93       NaN        NaN            NaN  8.000000  2144    0.24833
 94       NaN        NaN            NaN  8.000000  2144        NaN
 95       NaN        NaN            NaN  8.000000  2144        NaN
 96       NaN        NaN            NaN  8.000000  2144        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 92            NaN            NaN            NaN               NaN  ...
 93       0.787652       0.787252       0.787652          0.786037  ...
 94            NaN            NaN            NaN               NaN  ...
 95            NaN            NaN            NaN               NaN  ...
 96            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 92             NaN                NaN       NaN           NaN           NaN
 93             NaN                NaN       NaN           NaN           NaN
 94             NaN                NaN       NaN           NaN           NaN
 95           0.879           0.877664       NaN           NaN           NaN
 96             NaN                NaN  0.240392      0.793265      0.793045

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 92           NaN              NaN          NaN                     NaN
 93           NaN              NaN          NaN                     NaN
 94           NaN              NaN          NaN                     NaN
 95           NaN              NaN          NaN                     NaN
 96      0.793265         0.791825        0.752                1421.542

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 92                   NaN
 93                   NaN
 94                   NaN
 95                   NaN
 96                45.213

 [97 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                1       0.014574      0.600641       0.384785
 1              0                0       0.739259      0.253493       0.007247
 2              0                0       0.738909      0.255360       0.005730
 3              1                1       0.053911      0.602688       0.343401
 4              2                1       0.008103      0.696027       0.295870
 ...          ...              ...            ...           ...            ...
 1064           2                2       0.009219      0.374060       0.616721
 1065           0                2       0.010463      0.321691       0.667847
 1066           0                0       0.836793      0.159082       0.004125
 1067           1                2       0.017137      0.474162       0.508701
 1068           1                2       0.021199      0.392254       0.586547

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 449                            बाबा जमानामा नै जस्तो छ  Negative   Neutral
 304                                            बिमल जी  Positive   Neutral
 249                                          इस सुन्दर   Neutral  Positive
 301                                          राख्य मा?  Negative   Neutral
 168                                            कुरो नद  Positive  Negative
 ..                                                 ...       ...       ...
 463  असी हजर को अगाडी लिनु हजर को सपि हेर्रहेको क्ष...  Positive   Neutral
 247        लक अ kejariwal....done बय ओफ ignite....lvly  Positive  Negative
 53     यति राम्रो लै पानी हान्ने को कँदो चिक्नु पर्क्ष  Negative   Neutral
 102               जो विनर हुन्क्ष लग्ठो टोनी आज वायो इ  Negative  Positive
 408                          बरु पुब्ग खेलनी लै नि गार   Neutral  Positive

      confidence  token_length
 449    0.892533             8
 304    0.890281             5
 249    0.884921             4
 301    0.875613             6
 168    0.870467             6
 ..          ...           ...
 463    0.428391            40
 247    0.427660            23
 53     0.426461            19
 102    0.400343            16
 408    0.371622            14

 [500 rows x 5 columns]}

:

In [21]:
run_model(
    "muril",
    use_optuna=True,
    n_trials=5,
    search_epochs=5,
    use_llrd=True,
    layer_decay=0.85,
)

################################################################################
  RUNNING: MuRIL | Run: muril
  Model output : D:\Nepali sentiment\models\muril_muril
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\muril
  Tokenizer    : D:\Nepali sentiment\tokenizers\muril_muril
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): MuRIL
================================================================================
  Seed            : 42 (single)
  Optuna          : True
  LLRD            : True
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 2e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

config.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/206 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/113 [00:00<?, ?B/s]

  [Token Length Distribution]  (sampled 5000)
     90.0% → 31 tokens
     95.0% → 39 tokens
     97.0% → 45 tokens
     98.0% → 49 tokens
     99.0% → 55 tokens
     99.5% → 61 tokens
    100.0% → 92 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

--------------------------------------------------------------------------------
  PHASE 1: OPTUNA SEARCH (Train + Val only)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

pytorch_model.bin:   0%|          | 0.00/953M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[I 2026-09-29 15:28:52,204] A new study created in memory with name: no-name-a3466a1a-bb1f-41cb-aac0-803a9cce6448

model.safetensors:   0%|          | 0.00/953M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4692', 'grad_norm': '1.652', 'learning_rate': '3.85e-06', 'epoch': '1'}
{'eval_loss': '0.3972', 'eval_accuracy': '0.6183', 'eval_macro_f1': '0.5401', 'eval_micro_f1': '0.6183', 'eval_weighted_f1': '0.5353', 'eval_runtime': '0.7206', 'eval_samples_per_second': '1483', 'eval_steps_per_second': '47.18', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.469152
  Validation Loss     : 0.397155
  Validation Accuracy : 0.618335
  Validation Macro-F1 : 0.540055
==============================================================

model.safetensors:   0%|          | 0.00/953M [00:00<?, ?B/s]

{'loss': '0.3714', 'grad_norm': '7.691', 'learning_rate': '2.888e-06', 'epoch': '2'}
{'eval_loss': '0.3317', 'eval_accuracy': '0.6399', 'eval_macro_f1': '0.5845', 'eval_micro_f1': '0.6399', 'eval_weighted_f1': '0.5802', 'eval_runtime': '0.7315', 'eval_samples_per_second': '1461', 'eval_steps_per_second': '46.48', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.371401
  Validation Loss     : 0.331719
  Validation Accuracy : 0.639850
  Validation Macro-F1 : 0.584500
==============================================================

{'loss': '0.3251', 'grad_norm': '6.378', 'learning_rate': '1.926e-06', 'epoch': '3'}
{'eval_loss': '0.3034', 'eval_accuracy': '0.6857', 'eval_macro_f1': '0.6543', 'eval_micro_f1': '0.6857', 'eval_weighted_f1': '0.6511', 'eval_runtime': '0.7036', 'eval_samples_per_second': '1519', 'eval_steps_per_second': '48.32', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.325070
  Validation Loss     : 0.303425
  Validation Accuracy : 0.685688
  Validation Macro-F1 : 0.654253
==============================================================

{'loss': '0.3026', 'grad_norm': '4.451', 'learning_rate': '9.639e-07', 'epoch': '4'}
{'eval_loss': '0.2909', 'eval_accuracy': '0.696', 'eval_macro_f1': '0.6728', 'eval_micro_f1': '0.696', 'eval_weighted_f1': '0.67', 'eval_runtime': '0.7053', 'eval_samples_per_second': '1516', 'eval_steps_per_second': '48.21', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.302602
  Validation Loss     : 0.290852
  Validation Accuracy : 0.695978
  Validation Macro-F1 : 0.672820
==============================================================

{'loss': '0.292', 'grad_norm': '5.871', 'learning_rate': '1.798e-09', 'epoch': '5'}
{'eval_loss': '0.2868', 'eval_accuracy': '0.7072', 'eval_macro_f1': '0.6882', 'eval_micro_f1': '0.7072', 'eval_weighted_f1': '0.6857', 'eval_runtime': '0.6886', 'eval_samples_per_second': '1552', 'eval_steps_per_second': '49.37', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.291953
  Validation Loss     : 0.286819
  Validation Accuracy : 0.707203
  Validation Macro-F1 : 0.688203
==============================================================

{'train_runtime': '369.7', 'train_samples_per_second': '115.6', 'train_steps_per_second': '7.235', 'train_loss': '0.352', 'epoch': '5'}

[I 2026-09-29 15:35:04,828] Trial 0 finished with value: 0.6882033158305246 and parameters: {'learning_rate': 4.328450221293881e-06, 'weight_decay': 0.19063571821788408, 'warmup_ratio': 0.15979909127171077, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6882033158305246.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4882', 'grad_norm': '0.2022', 'learning_rate': '1.638e-06', 'epoch': '1'}
{'eval_loss': '0.4879', 'eval_accuracy': '0.3882', 'eval_macro_f1': '0.283', 'eval_micro_f1': '0.3882', 'eval_weighted_f1': '0.287', 'eval_runtime': '0.7095', 'eval_samples_per_second': '1507', 'eval_steps_per_second': '47.92', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.488187
  Validation Loss     : 0.487945
  Validation Accuracy : 0.388213
  Validation Macro-F1 : 0.283015
==============================================================

{'loss': '0.4817', 'grad_norm': '0.6368', 'learning_rate': '1.229e-06', 'epoch': '2'}
{'eval_loss': '0.4597', 'eval_accuracy': '0.5968', 'eval_macro_f1': '0.518', 'eval_micro_f1': '0.5968', 'eval_weighted_f1': '0.5133', 'eval_runtime': '0.7103', 'eval_samples_per_second': '1505', 'eval_steps_per_second': '47.87', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.481706
  Validation Loss     : 0.459726
  Validation Accuracy : 0.596819
  Validation Macro-F1 : 0.518007
==============================================================

{'loss': '0.4461', 'grad_norm': '2.916', 'learning_rate': '8.197e-07', 'epoch': '3'}
{'eval_loss': '0.4257', 'eval_accuracy': '0.6118', 'eval_macro_f1': '0.537', 'eval_micro_f1': '0.6118', 'eval_weighted_f1': '0.5321', 'eval_runtime': '0.6871', 'eval_samples_per_second': '1556', 'eval_steps_per_second': '49.48', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.446055
  Validation Loss     : 0.425656
  Validation Accuracy : 0.611787
  Validation Macro-F1 : 0.537048
==============================================================

{'loss': '0.4282', 'grad_norm': '5.153', 'learning_rate': '4.106e-07', 'epoch': '4'}
{'eval_loss': '0.4146', 'eval_accuracy': '0.6118', 'eval_macro_f1': '0.5371', 'eval_micro_f1': '0.6118', 'eval_weighted_f1': '0.5321', 'eval_runtime': '0.6891', 'eval_samples_per_second': '1551', 'eval_steps_per_second': '49.34', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.428222
  Validation Loss     : 0.414566
  Validation Accuracy : 0.611787
  Validation Macro-F1 : 0.537064
==============================================================

{'loss': '0.421', 'grad_norm': '1.754', 'learning_rate': '1.526e-09', 'epoch': '5'}
{'eval_loss': '0.4116', 'eval_accuracy': '0.6146', 'eval_macro_f1': '0.54', 'eval_micro_f1': '0.6146', 'eval_weighted_f1': '0.5351', 'eval_runtime': '0.6925', 'eval_samples_per_second': '1544', 'eval_steps_per_second': '49.1', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.421029
  Validation Loss     : 0.411557
  Validation Accuracy : 0.614593
  Validation Macro-F1 : 0.540017
==============================================================

{'train_runtime': '202.5', 'train_samples_per_second': '211.1', 'train_steps_per_second': '6.617', 'train_loss': '0.453', 'epoch': '5'}

[I 2026-09-29 15:38:30,314] Trial 1 finished with value: 0.5400171799173733 and parameters: {'learning_rate': 1.8408992080552519e-06, 'weight_decay': 0.021035886311957897, 'warmup_ratio': 0.1799264218662403, 'per_device_train_batch_size': 32}. Best is trial 0 with value: 0.6882033158305246.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4882', 'grad_norm': '0.1989', 'learning_rate': '9.641e-07', 'epoch': '1'}
{'eval_loss': '0.4881', 'eval_accuracy': '0.4004', 'eval_macro_f1': '0.3098', 'eval_micro_f1': '0.4004', 'eval_weighted_f1': '0.3143', 'eval_runtime': '0.717', 'eval_samples_per_second': '1491', 'eval_steps_per_second': '47.42', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.488212
  Validation Loss     : 0.488052
  Validation Accuracy : 0.400374
  Validation Macro-F1 : 0.309752
==============================================================

{'loss': '0.4857', 'grad_norm': '0.7354', 'learning_rate': '7.232e-07', 'epoch': '2'}
{'eval_loss': '0.4736', 'eval_accuracy': '0.594', 'eval_macro_f1': '0.5201', 'eval_micro_f1': '0.594', 'eval_weighted_f1': '0.5158', 'eval_runtime': '0.6989', 'eval_samples_per_second': '1530', 'eval_steps_per_second': '48.65', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.485737
  Validation Loss     : 0.473610
  Validation Accuracy : 0.594013
  Validation Macro-F1 : 0.520121
==============================================================

{'loss': '0.4574', 'grad_norm': '9.835', 'learning_rate': '4.823e-07', 'epoch': '3'}
{'eval_loss': '0.4373', 'eval_accuracy': '0.6099', 'eval_macro_f1': '0.5423', 'eval_micro_f1': '0.6099', 'eval_weighted_f1': '0.5377', 'eval_runtime': '0.6853', 'eval_samples_per_second': '1560', 'eval_steps_per_second': '49.61', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.457432
  Validation Loss     : 0.437325
  Validation Accuracy : 0.609916
  Validation Macro-F1 : 0.542309
==============================================================

{'loss': '0.4376', 'grad_norm': '3.939', 'learning_rate': '2.414e-07', 'epoch': '4'}
{'eval_loss': '0.4245', 'eval_accuracy': '0.6109', 'eval_macro_f1': '0.5383', 'eval_micro_f1': '0.6109', 'eval_weighted_f1': '0.5334', 'eval_runtime': '0.6946', 'eval_samples_per_second': '1539', 'eval_steps_per_second': '48.95', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.437632
  Validation Loss     : 0.424453
  Validation Accuracy : 0.610851
  Validation Macro-F1 : 0.538287
==============================================================

{'loss': '0.4307', 'grad_norm': '6.227', 'learning_rate': '4.503e-10', 'epoch': '5'}
{'eval_loss': '0.4212', 'eval_accuracy': '0.6155', 'eval_macro_f1': '0.5439', 'eval_micro_f1': '0.6155', 'eval_weighted_f1': '0.5391', 'eval_runtime': '0.6924', 'eval_samples_per_second': '1544', 'eval_steps_per_second': '49.1', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.430675
  Validation Loss     : 0.421236
  Validation Accuracy : 0.615529
  Validation Macro-F1 : 0.543947
==============================================================

{'train_runtime': '365.8', 'train_samples_per_second': '116.8', 'train_steps_per_second': '7.312', 'train_loss': '0.4599', 'epoch': '5'}

[I 2026-09-29 15:44:38,503] Trial 2 finished with value: 0.5439470143670888 and parameters: {'learning_rate': 1.083858126934475e-06, 'weight_decay': 0.19428287191077892, 'warmup_ratio': 0.17486639612006327, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6882033158305246.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.488', 'grad_norm': '0.2209', 'learning_rate': '1.823e-06', 'epoch': '1'}
{'eval_loss': '0.4854', 'eval_accuracy': '0.6174', 'eval_macro_f1': '0.5928', 'eval_micro_f1': '0.6174', 'eval_weighted_f1': '0.59', 'eval_runtime': '0.7533', 'eval_samples_per_second': '1419', 'eval_steps_per_second': '45.13', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.487983
  Validation Loss     : 0.485441
  Validation Accuracy : 0.617399
  Validation Macro-F1 : 0.592781
==============================================================

{'loss': '0.4441', 'grad_norm': '8.455', 'learning_rate': '1.367e-06', 'epoch': '2'}
{'eval_loss': '0.4046', 'eval_accuracy': '0.623', 'eval_macro_f1': '0.5544', 'eval_micro_f1': '0.623', 'eval_weighted_f1': '0.5498', 'eval_runtime': '0.7103', 'eval_samples_per_second': '1505', 'eval_steps_per_second': '47.87', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.444142
  Validation Loss     : 0.404636
  Validation Accuracy : 0.623012
  Validation Macro-F1 : 0.554410
==============================================================

{'loss': '0.3998', 'grad_norm': '19.28', 'learning_rate': '9.118e-07', 'epoch': '3'}
{'eval_loss': '0.378', 'eval_accuracy': '0.6258', 'eval_macro_f1': '0.5537', 'eval_micro_f1': '0.6258', 'eval_weighted_f1': '0.5488', 'eval_runtime': '0.7001', 'eval_samples_per_second': '1527', 'eval_steps_per_second': '48.57', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.399809
  Validation Loss     : 0.377974
  Validation Accuracy : 0.625819
  Validation Macro-F1 : 0.553653
==============================================================

{'loss': '0.3816', 'grad_norm': '15.76', 'learning_rate': '4.563e-07', 'epoch': '4'}
{'eval_loss': '0.3658', 'eval_accuracy': '0.6211', 'eval_macro_f1': '0.549', 'eval_micro_f1': '0.6211', 'eval_weighted_f1': '0.5439', 'eval_runtime': '0.6853', 'eval_samples_per_second': '1560', 'eval_steps_per_second': '49.62', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.381565
  Validation Loss     : 0.365771
  Validation Accuracy : 0.621141
  Validation Macro-F1 : 0.548967
==============================================================

{'loss': '0.3743', 'grad_norm': '25.28', 'learning_rate': '8.514e-10', 'epoch': '5'}
{'eval_loss': '0.3622', 'eval_accuracy': '0.6249', 'eval_macro_f1': '0.5565', 'eval_micro_f1': '0.6249', 'eval_weighted_f1': '0.5517', 'eval_runtime': '3.31', 'eval_samples_per_second': '323', 'eval_steps_per_second': '10.27', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.374273
  Validation Loss     : 0.362187
  Validation Accuracy : 0.624883
  Validation Macro-F1 : 0.556497
==============================================================

{'train_runtime': '394.2', 'train_samples_per_second': '108.4', 'train_steps_per_second': '6.786', 'train_loss': '0.4176', 'epoch': '5'}

[I 2026-09-29 15:51:16,020] Trial 3 finished with value: 0.5564970592484997 and parameters: {'learning_rate': 2.049268011541736e-06, 'weight_decay': 0.06780602616231217, 'warmup_ratio': 0.1287134647448357, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6882033158305246.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4518', 'grad_norm': '2.638', 'learning_rate': '9.745e-06', 'epoch': '1'}
{'eval_loss': '0.3639', 'eval_accuracy': '0.6221', 'eval_macro_f1': '0.5467', 'eval_micro_f1': '0.6221', 'eval_weighted_f1': '0.5419', 'eval_runtime': '1.535', 'eval_samples_per_second': '696.5', 'eval_steps_per_second': '22.15', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.451804
  Validation Loss     : 0.363937
  Validation Accuracy : 0.622077
  Validation Macro-F1 : 0.546711
==============================================================

{'loss': '0.3363', 'grad_norm': '0.8561', 'learning_rate': '7.311e-06', 'epoch': '2'}
{'eval_loss': '0.2925', 'eval_accuracy': '0.7044', 'eval_macro_f1': '0.6877', 'eval_micro_f1': '0.7044', 'eval_weighted_f1': '0.6853', 'eval_runtime': '1.976', 'eval_samples_per_second': '540.9', 'eval_steps_per_second': '17.2', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.336266
  Validation Loss     : 0.292476
  Validation Accuracy : 0.704397
  Validation Macro-F1 : 0.687670
==============================================================

{'loss': '0.2827', 'grad_norm': '9.267', 'learning_rate': '4.877e-06', 'epoch': '3'}
{'eval_loss': '0.2646', 'eval_accuracy': '0.7334', 'eval_macro_f1': '0.7267', 'eval_micro_f1': '0.7334', 'eval_weighted_f1': '0.7251', 'eval_runtime': '1.914', 'eval_samples_per_second': '558.5', 'eval_steps_per_second': '17.76', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.282727
  Validation Loss     : 0.264571
  Validation Accuracy : 0.733396
  Validation Macro-F1 : 0.726728
==============================================================

{'loss': '0.2546', 'grad_norm': '7.785', 'learning_rate': '2.443e-06', 'epoch': '4'}
{'eval_loss': '0.2529', 'eval_accuracy': '0.7437', 'eval_macro_f1': '0.7389', 'eval_micro_f1': '0.7437', 'eval_weighted_f1': '0.7373', 'eval_runtime': '1.723', 'eval_samples_per_second': '620.5', 'eval_steps_per_second': '19.74', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.254581
  Validation Loss     : 0.252868
  Validation Accuracy : 0.743686
  Validation Macro-F1 : 0.738856
==============================================================

{'loss': '0.2426', 'grad_norm': '3.315', 'learning_rate': '9.082e-09', 'epoch': '5'}
{'eval_loss': '0.2485', 'eval_accuracy': '0.7456', 'eval_macro_f1': '0.7409', 'eval_micro_f1': '0.7456', 'eval_weighted_f1': '0.7393', 'eval_runtime': '1.845', 'eval_samples_per_second': '579.4', 'eval_steps_per_second': '18.43', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.242563
  Validation Loss     : 0.248519
  Validation Accuracy : 0.745557
  Validation Macro-F1 : 0.740885
==============================================================

{'train_runtime': '293.1', 'train_samples_per_second': '145.9', 'train_steps_per_second': '4.572', 'train_loss': '0.3136', 'epoch': '5'}

[I 2026-09-29 15:56:16,088] Trial 4 finished with value: 0.7408853591083373 and parameters: {'learning_rate': 1.0952662748632564e-05, 'weight_decay': 0.036503833523887946, 'warmup_ratio': 0.09382169728028272, 'per_device_train_batch_size': 32}. Best is trial 4 with value: 0.7408853591083373.

  BEST OPTUNA Macro-F1: 0.7409
    learning_rate                      : 1.0952662748632564e-05
    weight_decay                       : 0.036503833523887946
    warmup_ratio                       : 0.09382169728028272
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: google/muril-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/8
==============================================================
  Train Loss          : 0.406886
  Validation Loss     : 0.373655
  Validation Accuracy : 0.616464
  Validation Macro-F1 : 0.544290
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/8
==============================================================
  Train Loss          : 0.301111
  Validation Loss     : 0.289992
  Validation Accuracy : 0.722170
  Validation Macro-F1 : 0.709945
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/8
==============================================================
  Train Loss          : 0.279697
  Validation Loss     : 0.256140
  Validation Accuracy : 0.738073
  Validation Macro-F1 : 0.734191
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.216986
  Validation Loss     : 0.236818
  Validation Accuracy : 0.748363
  Validation Macro-F1 : 0.748411
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/8
==============================================================
  Train Loss          : 0.194646
  Validation Loss     : 0.225710
  Validation Accuracy : 0.764266
  Validation Macro-F1 : 0.761477
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 6/8
==============================================================
  Train Loss          : 0.198907
  Validation Loss     : 0.223605
  Validation Accuracy : 0.758653
  Validation Macro-F1 : 0.754435
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 7/8
==============================================================
  Train Loss          : 0.168705
  Validation Loss     : 0.218171
  Validation Accuracy : 0.769878
  Validation Macro-F1 : 0.770054
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.200310
  Validation Loss     : 0.216974
  Validation Accuracy : 0.769878
  Validation Macro-F1 : 0.769556
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.200310
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.200310
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8207
  Val   Macro-F1 : 0.7701
  Gap            : +0.0507
  Status         : ⚠️ Potential overfitting (Gap > 0.05)

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.5126
  Balanced Accuracy : 0.5098
  Macro-F1          : 0.4990
  Weighted-F1       : 0.4998
  MCC               : 0.2799
  Macro ROC-AUC     : 0.7071
  Val→Test Gap      : +0.2710

[Bootstrap CI (n=1000)]
  accuracy            : 0.5128 [0.4827, 0.5426]
  macro_f1            : 0.4989 [0.4657, 0.5289]
  weighted_f1         : 0.5000 [0.4657, 0.5306]
  mcc                 : 0.2803 [0.2344, 0.3240]
  balanced_accuracy   : 0.5101 [0.4801, 0.5381]

[Calibration / ECE]
  Positive       : ECE = 0.1573 ⚠️
  Neutral        : ECE = 0.0880 🟠
  Negative       : ECE = 0.0771 🟠
  Mean Class ECE  : 0.1074

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8207
  Val   F1  : 0.7701
  Test  F1  : 0.4990
  Train→Val : +0.0507
  Val→Test  : +0.2710
  Status    : ⚠️ Potential overfitting (Gap > 0.05)

[Error Analysis]
  Saved 521 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\muril_muril\model
  Tokenizer → D:\Nepali sentiment\tokenizers\muril_muril
  Plots     → D:\Nepali sentiment\models\muril_muril\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ muril | Val F1: 0.7701 | Test F1: 0.4990

{'label': 'MuRIL',
 'best_hparams': {'learning_rate': 1.0952662748632564e-05,
  'weight_decay': 0.036503833523887946,
  'warmup_ratio': 0.09382169728028272,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.5126286248830683,
 'test_macro_f1': 0.49903928330553615,
 'test_weighted_f1': 0.4997914578720189,
 'balanced_accuracy': 0.5098354073484913,
 'mcc': 0.2799081850609773,
 'macro_roc_auc': np.float64(0.7071498406024802),
 'mean_class_ece': 0.10743394710116567,
 'per_class_f1': {'Positive': 0.4197002141327623,
  'Neutral': 0.4778972520908005,
  'Negative': 0.5995203836930456},
 'roc_auc': {'Positive': 0.7427745664739884,
  'Neutral': 0.6275120641344956,
  'Negative': 0.7511628911989565},
 'pr_auc': {'Positive': 0.6375165569672671,
  'Neutral': 0.4646891474168213,
  'Negative': 0.6058495120482558},
 'train_f1': 0.8207478980341049,
 'val_f1': 0.7700544918297076,
 'train_val_gap': 0.05069340620439722,
 'val_test_gap': 0.2710152085241715,
 'gap_status': '⚠️ Potential overfitting (Gap > 0.05)',
 'bootstrap_ci': {'accuracy': (0.5127848456501404,
   0.4826707202993452,
   0.5425631431244153),
  'macro_f1': (0.4989134838992355, 0.46572400693706456, 0.5289054042203192),
  'weighted_f1': (0.49995699701071894, 0.46570657697504114, 0.530566220203406),
  'mcc': (0.2803498057305938, 0.23442820956463106, 0.3240351485662226),
  'balanced_accuracy': (0.5101403783524757,
   0.4801101428408977,
   0.5381290802214269),
  'per_class_f1': {'Positive': (0.4198034308759481,
    0.3610501366963577,
    0.47620624408703877),
   'Neutral': (0.4770649866008275, 0.43573457518848724, 0.5184353131933778),
   'Negative': (0.599872034220931, 0.5583126550868487, 0.6397326344008808)}},
 'ece_scores': {'Positive': 0.15726735673572997,
  'Neutral': 0.08796103077028485,
  'Negative': 0.07707345379748223},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.809917  0.283237  0.419700   346.000000
 Neutral        0.423729  0.547945  0.477897   365.000000
 Negative       0.525210  0.698324  0.599520   358.000000
 accuracy       0.512629  0.512629  0.512629     0.512629
 macro avg      0.586285  0.509835  0.499039  1069.000000
 weighted avg   0.582711  0.512629  0.499791  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.487934   0.253372   0.000000e+00  0.003731     1        NaN
 1   0.488113   0.175576   1.301306e-06  0.093284    25        NaN
 2   0.488394   0.055208   2.656834e-06  0.186567    50        NaN
 3   0.488160   0.040817   4.012362e-06  0.279851    75        NaN
 4   0.488119   0.110501   5.367889e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 92  0.200310   7.092850   1.127978e-07  7.929104  2125        NaN
 93       NaN        NaN            NaN  8.000000  2144   0.216974
 94       NaN        NaN            NaN  8.000000  2144        NaN
 95       NaN        NaN            NaN  8.000000  2144        NaN
 96       NaN        NaN            NaN  8.000000  2144        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 92            NaN            NaN            NaN               NaN  ...
 93       0.769878       0.769556       0.769878          0.768056  ...
 94            NaN            NaN            NaN               NaN  ...
 95            NaN            NaN            NaN               NaN  ...
 96            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 92             NaN                NaN       NaN           NaN           NaN
 93             NaN                NaN       NaN           NaN           NaN
 94             NaN                NaN       NaN           NaN           NaN
 95            0.82            0.81859       NaN           NaN           NaN
 96             NaN                NaN  0.218171      0.769878      0.770054

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 92           NaN              NaN          NaN                     NaN
 93           NaN              NaN          NaN                     NaN
 94           NaN              NaN          NaN                     NaN
 95           NaN              NaN          NaN                     NaN
 96      0.769878         0.768578       0.7105                1504.545

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 92                   NaN
 93                   NaN
 94                   NaN
 95                   NaN
 96                47.853

 [97 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                1       0.113727      0.566382       0.319891
 1              0                0       0.669503      0.247351       0.083146
 2              0                1       0.304158      0.537081       0.158761
 3              1                2       0.074243      0.458358       0.467399
 4              2                1       0.159618      0.597705       0.242677
 ...          ...              ...            ...           ...            ...
 1064           2                1       0.130741      0.595169       0.274090
 1065           0                2       0.070843      0.335998       0.593160
 1066           0                0       0.743657      0.173556       0.082787
 1067           1                1       0.201890      0.567320       0.230790
 1068           1                1       0.084732      0.535524       0.379744

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 36                               बिस्त great.rupak होल  Negative  Positive
 518                          सलाम क्ष दिदि बिचार बनु 😭   Neutral  Positive
 264                                          इस सुन्दर   Neutral  Positive
 432                       को पम प्रकाश आमाले जिन्दाबाद   Neutral  Positive
 194  अनि बिचारी यो नानीलाई पो साह्रै माया लाग्छ यार...   Neutral  Positive
 ..                                                 ...       ...       ...
 240                            पहिलेकै आवाज चैन्क्ष मा   Neutral  Positive
 26   मलाई मेरो बाट एकदम मान्न परेको मन्क्षे विवेक स...  Positive   Neutral
 353  लिला तपाई को जति हेर्क्षु हर्क्षु दिल उन्क्ष म...  Positive   Neutral
 111                 यो मा दाम्दर समिर नीलु बब्बाल छ इन  Positive   Neutral
 362                                                  🙏  Positive   Neutral

      confidence  token_length
 36     0.746157             9
 518    0.725021            10
 264    0.720090             4
 432    0.717622             9
 194    0.674126            22
 ..          ...           ...
 240    0.444141             9
 26     0.441613            15
 353    0.438195            23
 111    0.437438            15
 362    0.403397             3

 [521 rows x 5 columns]}

In [ ]:
# Run mBERT with your specific best hyperparameters
run_model(
    "mbert",
    run_name="mbert_best_hps",      # Custom name to identify this run
    clean_old=True,                 # Clears previous mBERT runs to save disk space
    use_optuna=False,               # Disable Optuna search since we have fixed HPs
    use_llrd=True,                  # Keep Layer-wise Learning Rate Decay enabled (set to False if you want to test without it)
    learning_rate=1.0952662748632564e-05,
    weight_decay=0.036503833523887946,
    warmup_ratio=0.09382169728028272,
    batch_size=32                   # This maps to per_device_train_batch_size in the pipeline
)

################################################################################
  RUNNING: mBERT | Run: mbert_best_hps
  Model output : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\mbert_mbert_best_hps
  Checkpoints  : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\training_checkpoints\mbert_best_hps
  Tokenizer    : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\tokenizers\mbert_mbert_best_hps
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): mBERT
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : True
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1.0952662748632564e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 41 tokens
     95.0% → 50 tokens
     97.0% → 57 tokens
     98.0% → 61 tokens
     99.0% → 68 tokens
     99.5% → 76 tokens
    100.0% → 110 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8544 | Val: 1068 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1.0952662748632564e-05
    weight_decay                       : 0.036503833523887946
    warmup_ratio                       : 0.09382169728028272
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/8
==============================================================
  Train Loss          : 0.284635
  Validation Loss     : 0.253392
  Validation Accuracy : 0.720974
  Validation Macro-F1 : 0.720984
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/8
==============================================================
  Train Loss          : 0.229438
  Validation Loss     : 0.219725
  Validation Accuracy : 0.751873
  Validation Macro-F1 : 0.753711
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/8
==============================================================
  Train Loss          : 0.203703
  Validation Loss     : 0.214737
  Validation Accuracy : 0.774345
  Validation Macro-F1 : 0.773872
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.174930
  Validation Loss     : 0.218888
  Validation Accuracy : 0.771536
  Validation Macro-F1 : 0.768410
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/8
==============================================================
  Train Loss          : 0.146363
  Validation Loss     : 0.232518
  Validation Accuracy : 0.783708
  Validation Macro-F1 : 0.784529
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 6/8
==============================================================
  Train Loss          : 0.123209
  Validation Loss     : 0.242141
  Validation Accuracy : 0.784644
  Validation Macro-F1 : 0.784856
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 7/8
==============================================================
  Train Loss          : 0.119519
  Validation Loss     : 0.247837
  Validation Accuracy : 0.785581
  Validation Macro-F1 : 0.786774
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.096933
  Validation Loss     : 0.251865
  Validation Accuracy : 0.789326
  Validation Macro-F1 : 0.789355
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.096933
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.096933
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.9150
  Val   Macro-F1 : 0.7894
  Gap            : +0.1257
  Status         : ⚠️ Potential overfitting (Gap > 0.05)

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.7811
  Balanced Accuracy : 0.7816
  Macro-F1          : 0.7804
  Weighted-F1       : 0.7798
  MCC               : 0.6720
  Macro ROC-AUC     : 0.9151
  Val→Test Gap      : +0.0090

[Bootstrap CI (n=1000)]
  accuracy            : 0.7811 [0.7558, 0.8064]
  macro_f1            : 0.7801 [0.7548, 0.8052]
  weighted_f1         : 0.7798 [0.7546, 0.8052]
  mcc                 : 0.6720 [0.6340, 0.7103]
  balanced_accuracy   : 0.7816 [0.7572, 0.8063]

[Calibration / ECE]
  Positive       : ECE = 0.0391 ✅
  Neutral        : ECE = 0.0530 🟠
  Negative       : ECE = 0.0290 ✅
  Mean Class ECE  : 0.0404

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.9150
  Val   F1  : 0.7894
  Test  F1  : 0.7804
  Train→Val : +0.1257
  Val→Test  : +0.0090
  Status    : ⚠️ Potential overfitting (Gap > 0.05)

[Error Analysis]
  Saved 234 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\mbert_mbert_best_hps\model
  Tokenizer → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\tokenizers\mbert_mbert_best_hps
  Plots     → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\mbert_mbert_best_hps\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ mbert_best_hps | Val F1: 0.7894 | Test F1: 0.7804

{'label': 'mBERT',
 'best_hparams': {'learning_rate': 1.0952662748632564e-05,
  'weight_decay': 0.036503833523887946,
  'warmup_ratio': 0.09382169728028272,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.7811038353601497,
 'test_macro_f1': 0.7803611398447545,
 'test_weighted_f1': 0.7798109198131308,
 'balanced_accuracy': 0.7816253924141243,
 'mcc': 0.6719933058570462,
 'macro_roc_auc': np.float64(0.9151246681909947),
 'mean_class_ece': 0.040384989773136155,
 'per_class_f1': {'Positive': 0.8534850640113798,
  'Neutral': 0.6897546897546898,
  'Negative': 0.7978436657681941},
 'roc_auc': {'Positive': 0.9561246418338109,
  'Neutral': 0.8587008619538145,
  'Negative': 0.9305485007853588},
 'pr_auc': {'Positive': 0.9222389036091942,
  'Neutral': 0.7487475252046336,
  'Negative': 0.8696338432716411},
 'train_f1': 0.9150092708464577,
 'val_f1': 0.7893549024332783,
 'train_val_gap': 0.12565436841317934,
 'val_test_gap': 0.008993762588523802,
 'gap_status': '⚠️ Potential overfitting (Gap > 0.05)',
 'bootstrap_ci': {'accuracy': (0.781091674462114,
   0.7558465855940131,
   0.8063610851262862),
  'macro_f1': (0.7801224897242105, 0.7548268678558672, 0.8051828012320394),
  'weighted_f1': (0.7797806648179911, 0.7546040061907859, 0.8051929774134663),
  'mcc': (0.6719762479115977, 0.633995605173247, 0.7102874627645025),
  'balanced_accuracy': (0.7816050937532434,
   0.7571671107984276,
   0.8063190695240259),
  'per_class_f1': {'Positive': (0.8532110244961928,
    0.8251495398773007,
    0.8804351648015655),
   'Neutral': (0.6896207679744277, 0.6490578311230485, 0.7294141755062681),
   'Negative': (0.7975356767020111, 0.7646999445807933, 0.8299652199762187)}},
 'ece_scores': {'Positive': 0.039120057676165214,
  'Neutral': 0.05300978853448292,
  'Negative': 0.02902512310876034},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.847458  0.859599  0.853485   349.000000
 Neutral        0.713433  0.667598  0.689755   358.000000
 Negative       0.778947  0.817680  0.797844   362.000000
 accuracy       0.781104  0.781104  0.781104     0.781104
 macro avg      0.779946  0.781625  0.780361  1069.000000
 weighted avg   0.779374  0.781104  0.779811  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.488269   2.152632   0.000000e+00  0.003745     1        NaN
 1   0.488596   2.806817   1.307781e-06  0.093633    25        NaN
 2   0.486444   2.089976   2.670052e-06  0.187266    50        NaN
 3   0.471500   2.698016   4.032324e-06  0.280899    75        NaN
 4   0.440687   2.975599   5.394595e-06  0.374532   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 92  0.096933   7.976958   6.792349e-08  7.958801  2125        NaN
 93       NaN        NaN            NaN  8.000000  2136   0.251865
 94       NaN        NaN            NaN  8.000000  2136        NaN
 95       NaN        NaN            NaN  8.000000  2136        NaN
 96       NaN        NaN            NaN  8.000000  2136        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 92            NaN            NaN            NaN               NaN  ...
 93       0.789326       0.789355       0.789326          0.788728  ...
 94            NaN            NaN            NaN               NaN  ...
 95            NaN            NaN            NaN               NaN  ...
 96            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 92             NaN                NaN       NaN           NaN           NaN
 93             NaN                NaN       NaN           NaN           NaN
 94             NaN                NaN       NaN           NaN           NaN
 95           0.915           0.914236       NaN           NaN           NaN
 96             NaN                NaN  0.251865      0.789326      0.789355

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 92           NaN              NaN          NaN                     NaN
 93           NaN              NaN          NaN                     NaN
 94           NaN              NaN          NaN                     NaN
 95           NaN              NaN          NaN                     NaN
 96      0.789326         0.788728       1.6754                 637.476

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 92                   NaN
 93                   NaN
 94                   NaN
 95                   NaN
 96                20.294

 [97 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                0       0.852619      0.140004       0.007377
 1              2                2       0.006965      0.473260       0.519775
 2              0                1       0.015546      0.661032       0.323422
 3              1                1       0.393642      0.555125       0.051233
 4              2                2       0.004795      0.372083       0.623122
 ...          ...              ...            ...           ...            ...
 1064           2                2       0.008615      0.377935       0.613450
 1065           2                2       0.004783      0.203365       0.791853
 1066           2                1       0.156966      0.620811       0.222223
 1067           0                0       0.803354      0.183862       0.012784
 1068           1                1       0.428723      0.563546       0.007731

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 108             Makune has gone to lick Mahat's soles.   Neutral  Negative
 86         Do I need to teach you a lesson, Kapil sir?  Negative   Neutral
 138  Now, I wonder on which day the divorce will ha...  Negative   Neutral
 9    Such an innocent boy Laure, love you both, bes...   Neutral  Positive
 102  Rupesh sir, in the next video, you should also...  Positive   Neutral
 ..                                                 ...       ...       ...
 151                               only one bold leader  Positive  Negative
 191  Madhu Chhetri is 100% right; I watched the ent...  Positive   Neutral
 26   Good! You can't live off Nepal and sing praise...  Negative   Neutral
 211  Stupid Pranesh, Kabita Sapkota, and Nidhi. Pas...   Neutral  Negative
 117  me watching this :- oh, I have the worst handw...   Neutral  Positive

      confidence  token_length
 108    0.905476            16
 86     0.902519            16
 138    0.895219            15
 9      0.889242            28
 102    0.881114            25
 ..          ...           ...
 151    0.413639             6
 191    0.403271            33
 26     0.402896            23
 211    0.402078            34
 117    0.392785            21

 [234 rows x 5 columns]}

In [22]:
run_model(
    "mbert",
    use_optuna=True,
    n_trials=5,
    search_epochs=5,
    use_llrd=True,
    layer_decay=0.85,
)

################################################################################
  RUNNING: mBERT | Run: mbert
  Model output : D:\Nepali sentiment\models\mbert_mbert
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\mbert
  Tokenizer    : D:\Nepali sentiment\tokenizers\mbert_mbert
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): mBERT
================================================================================
  Seed            : 42 (single)
  Optuna          : True
  LLRD            : True
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 2e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

  [Token Length Distribution]  (sampled 5000)
     90.0% → 61 tokens
     95.0% → 77 tokens
     97.0% → 87 tokens
     98.0% → 95 tokens
     99.0% → 107 tokens
     99.5% → 119 tokens
    100.0% → 194 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

--------------------------------------------------------------------------------
  PHASE 1: OPTUNA SEARCH (Train + Val only)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[I 2026-09-29 16:07:23,010] A new study created in memory with name: no-name-aa16d648-c355-4782-ac6a-6d8422e50720

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4476', 'grad_norm': '9.662', 'learning_rate': '3.85e-06', 'epoch': '1'}
{'eval_loss': '0.3484', 'eval_accuracy': '0.6024', 'eval_macro_f1': '0.597', 'eval_micro_f1': '0.6024', 'eval_weighted_f1': '0.5954', 'eval_runtime': '1.092', 'eval_samples_per_second': '978.9', 'eval_steps_per_second': '31.13', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.447551
  Validation Loss     : 0.348407
  Validation Accuracy : 0.602432
  Validation Macro-F1 : 0.596988
==============================================================

{'loss': '0.3394', 'grad_norm': '8.686', 'learning_rate': '2.888e-06', 'epoch': '2'}
{'eval_loss': '0.2975', 'eval_accuracy': '0.6679', 'eval_macro_f1': '0.669', 'eval_micro_f1': '0.6679', 'eval_weighted_f1': '0.6675', 'eval_runtime': '1.091', 'eval_samples_per_second': '980', 'eval_steps_per_second': '31.17', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.339420
  Validation Loss     : 0.297486
  Validation Accuracy : 0.667914
  Validation Macro-F1 : 0.669002
==============================================================

{'loss': '0.303', 'grad_norm': '38.78', 'learning_rate': '1.926e-06', 'epoch': '3'}
{'eval_loss': '0.2941', 'eval_accuracy': '0.6782', 'eval_macro_f1': '0.6755', 'eval_micro_f1': '0.6782', 'eval_weighted_f1': '0.6741', 'eval_runtime': '1.087', 'eval_samples_per_second': '983.8', 'eval_steps_per_second': '31.29', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.303046
  Validation Loss     : 0.294055
  Validation Accuracy : 0.678204
  Validation Macro-F1 : 0.675529
==============================================================

{'loss': '0.2807', 'grad_norm': '18.26', 'learning_rate': '9.639e-07', 'epoch': '4'}
{'eval_loss': '0.2807', 'eval_accuracy': '0.6885', 'eval_macro_f1': '0.6873', 'eval_micro_f1': '0.6885', 'eval_weighted_f1': '0.6858', 'eval_runtime': '1.226', 'eval_samples_per_second': '871.8', 'eval_steps_per_second': '27.73', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.280695
  Validation Loss     : 0.280668
  Validation Accuracy : 0.688494
  Validation Macro-F1 : 0.687268
==============================================================

{'loss': '0.2694', 'grad_norm': '22.04', 'learning_rate': '1.798e-09', 'epoch': '5'}
{'eval_loss': '0.2796', 'eval_accuracy': '0.6997', 'eval_macro_f1': '0.6989', 'eval_micro_f1': '0.6997', 'eval_weighted_f1': '0.6975', 'eval_runtime': '1.086', 'eval_samples_per_second': '984.3', 'eval_steps_per_second': '31.31', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.269364
  Validation Loss     : 0.279568
  Validation Accuracy : 0.699719
  Validation Macro-F1 : 0.698887
==============================================================

{'train_runtime': '327.9', 'train_samples_per_second': '130.4', 'train_steps_per_second': '8.158', 'train_loss': '0.328', 'epoch': '5'}

[I 2026-09-29 16:12:52,447] Trial 0 finished with value: 0.6988869871929208 and parameters: {'learning_rate': 4.328450221293881e-06, 'weight_decay': 0.19063571821788408, 'warmup_ratio': 0.15979909127171077, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6988869871929208.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4851', 'grad_norm': '4.283', 'learning_rate': '1.638e-06', 'epoch': '1'}
{'eval_loss': '0.4642', 'eval_accuracy': '0.4715', 'eval_macro_f1': '0.4607', 'eval_micro_f1': '0.4715', 'eval_weighted_f1': '0.4593', 'eval_runtime': '1.092', 'eval_samples_per_second': '978.9', 'eval_steps_per_second': '31.14', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.485064
  Validation Loss     : 0.464176
  Validation Accuracy : 0.471469
  Validation Macro-F1 : 0.460685
==============================================================

{'loss': '0.434', 'grad_norm': '12.29', 'learning_rate': '1.229e-06', 'epoch': '2'}
{'eval_loss': '0.3853', 'eval_accuracy': '0.5575', 'eval_macro_f1': '0.5551', 'eval_micro_f1': '0.5575', 'eval_weighted_f1': '0.5536', 'eval_runtime': '1.09', 'eval_samples_per_second': '980.9', 'eval_steps_per_second': '31.2', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.433961
  Validation Loss     : 0.385261
  Validation Accuracy : 0.557530
  Validation Macro-F1 : 0.555086
==============================================================

{'loss': '0.3893', 'grad_norm': '17.21', 'learning_rate': '8.197e-07', 'epoch': '3'}
{'eval_loss': '0.3581', 'eval_accuracy': '0.5987', 'eval_macro_f1': '0.5967', 'eval_micro_f1': '0.5987', 'eval_weighted_f1': '0.5951', 'eval_runtime': '1.1', 'eval_samples_per_second': '972', 'eval_steps_per_second': '30.92', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.389258
  Validation Loss     : 0.358059
  Validation Accuracy : 0.598690
  Validation Macro-F1 : 0.596661
==============================================================

{'loss': '0.3716', 'grad_norm': '19.79', 'learning_rate': '4.106e-07', 'epoch': '4'}
{'eval_loss': '0.3459', 'eval_accuracy': '0.6127', 'eval_macro_f1': '0.612', 'eval_micro_f1': '0.6127', 'eval_weighted_f1': '0.6104', 'eval_runtime': '1.085', 'eval_samples_per_second': '985.7', 'eval_steps_per_second': '31.35', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.371560
  Validation Loss     : 0.345917
  Validation Accuracy : 0.612722
  Validation Macro-F1 : 0.611971
==============================================================

{'loss': '0.3621', 'grad_norm': '13.28', 'learning_rate': '1.526e-09', 'epoch': '5'}
{'eval_loss': '0.3429', 'eval_accuracy': '0.6221', 'eval_macro_f1': '0.6212', 'eval_micro_f1': '0.6221', 'eval_weighted_f1': '0.6196', 'eval_runtime': '1.089', 'eval_samples_per_second': '981.5', 'eval_steps_per_second': '31.22', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.362143
  Validation Loss     : 0.342850
  Validation Accuracy : 0.622077
  Validation Macro-F1 : 0.621157
==============================================================

{'train_runtime': '226.2', 'train_samples_per_second': '189', 'train_steps_per_second': '5.925', 'train_loss': '0.4084', 'epoch': '5'}

[I 2026-09-29 16:16:40,191] Trial 1 finished with value: 0.6211569337712975 and parameters: {'learning_rate': 1.8408992080552519e-06, 'weight_decay': 0.021035886311957897, 'warmup_ratio': 0.1799264218662403, 'per_device_train_batch_size': 32}. Best is trial 0 with value: 0.6988869871929208.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4863', 'grad_norm': '4.613', 'learning_rate': '9.641e-07', 'epoch': '1'}
{'eval_loss': '0.4674', 'eval_accuracy': '0.4687', 'eval_macro_f1': '0.4379', 'eval_micro_f1': '0.4687', 'eval_weighted_f1': '0.4365', 'eval_runtime': '1.077', 'eval_samples_per_second': '992.7', 'eval_steps_per_second': '31.57', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.486294
  Validation Loss     : 0.467432
  Validation Accuracy : 0.468662
  Validation Macro-F1 : 0.437886
==============================================================

{'loss': '0.4399', 'grad_norm': '7.724', 'learning_rate': '7.232e-07', 'epoch': '2'}
{'eval_loss': '0.3987', 'eval_accuracy': '0.5388', 'eval_macro_f1': '0.537', 'eval_micro_f1': '0.5388', 'eval_weighted_f1': '0.5356', 'eval_runtime': '1.12', 'eval_samples_per_second': '954.8', 'eval_steps_per_second': '30.37', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.439893
  Validation Loss     : 0.398743
  Validation Accuracy : 0.538821
  Validation Macro-F1 : 0.537031
==============================================================

{'loss': '0.3977', 'grad_norm': '15.13', 'learning_rate': '4.823e-07', 'epoch': '3'}
{'eval_loss': '0.3689', 'eval_accuracy': '0.5828', 'eval_macro_f1': '0.5799', 'eval_micro_f1': '0.5828', 'eval_weighted_f1': '0.5783', 'eval_runtime': '1.095', 'eval_samples_per_second': '976.2', 'eval_steps_per_second': '31.05', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.397712
  Validation Loss     : 0.368894
  Validation Accuracy : 0.582788
  Validation Macro-F1 : 0.579856
==============================================================

{'loss': '0.3798', 'grad_norm': '15.3', 'learning_rate': '2.414e-07', 'epoch': '4'}
{'eval_loss': '0.3569', 'eval_accuracy': '0.5987', 'eval_macro_f1': '0.5981', 'eval_micro_f1': '0.5987', 'eval_weighted_f1': '0.5966', 'eval_runtime': '1.11', 'eval_samples_per_second': '963.3', 'eval_steps_per_second': '30.64', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.379764
  Validation Loss     : 0.356858
  Validation Accuracy : 0.598690
  Validation Macro-F1 : 0.598077
==============================================================

{'loss': '0.3743', 'grad_norm': '16.89', 'learning_rate': '4.503e-10', 'epoch': '5'}
{'eval_loss': '0.3546', 'eval_accuracy': '0.6015', 'eval_macro_f1': '0.6002', 'eval_micro_f1': '0.6015', 'eval_weighted_f1': '0.5987', 'eval_runtime': '1.082', 'eval_samples_per_second': '987.9', 'eval_steps_per_second': '31.42', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.374284
  Validation Loss     : 0.354608
  Validation Accuracy : 0.601497
  Validation Macro-F1 : 0.600224
==============================================================

{'train_runtime': '331.5', 'train_samples_per_second': '129', 'train_steps_per_second': '8.07', 'train_loss': '0.4156', 'epoch': '5'}

[I 2026-09-29 16:22:13,182] Trial 2 finished with value: 0.6002238288911446 and parameters: {'learning_rate': 1.083858126934475e-06, 'weight_decay': 0.19428287191077892, 'warmup_ratio': 0.17486639612006327, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6988869871929208.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.476', 'grad_norm': '7.672', 'learning_rate': '1.823e-06', 'epoch': '1'}
{'eval_loss': '0.4169', 'eval_accuracy': '0.5304', 'eval_macro_f1': '0.521', 'eval_micro_f1': '0.5304', 'eval_weighted_f1': '0.5194', 'eval_runtime': '1.084', 'eval_samples_per_second': '986.6', 'eval_steps_per_second': '31.38', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.475989
  Validation Loss     : 0.416913
  Validation Accuracy : 0.530402
  Validation Macro-F1 : 0.520990
==============================================================

{'loss': '0.3889', 'grad_norm': '7.819', 'learning_rate': '1.367e-06', 'epoch': '2'}
{'eval_loss': '0.3474', 'eval_accuracy': '0.6052', 'eval_macro_f1': '0.602', 'eval_micro_f1': '0.6052', 'eval_weighted_f1': '0.6006', 'eval_runtime': '1.088', 'eval_samples_per_second': '982.9', 'eval_steps_per_second': '31.26', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.388926
  Validation Loss     : 0.347389
  Validation Accuracy : 0.605239
  Validation Macro-F1 : 0.602006
==============================================================

{'loss': '0.354', 'grad_norm': '25.02', 'learning_rate': '9.118e-07', 'epoch': '3'}
{'eval_loss': '0.3261', 'eval_accuracy': '0.6427', 'eval_macro_f1': '0.6414', 'eval_micro_f1': '0.6427', 'eval_weighted_f1': '0.6398', 'eval_runtime': '1.087', 'eval_samples_per_second': '983.5', 'eval_steps_per_second': '31.28', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.354049
  Validation Loss     : 0.326095
  Validation Accuracy : 0.642657
  Validation Macro-F1 : 0.641368
==============================================================

{'loss': '0.3357', 'grad_norm': '23.69', 'learning_rate': '4.563e-07', 'epoch': '4'}
{'eval_loss': '0.3152', 'eval_accuracy': '0.6548', 'eval_macro_f1': '0.6548', 'eval_micro_f1': '0.6548', 'eval_weighted_f1': '0.6534', 'eval_runtime': '1.083', 'eval_samples_per_second': '987', 'eval_steps_per_second': '31.39', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.335702
  Validation Loss     : 0.315243
  Validation Accuracy : 0.654818
  Validation Macro-F1 : 0.654850
==============================================================

{'loss': '0.3275', 'grad_norm': '20.27', 'learning_rate': '8.514e-10', 'epoch': '5'}
{'eval_loss': '0.3142', 'eval_accuracy': '0.6586', 'eval_macro_f1': '0.6582', 'eval_micro_f1': '0.6586', 'eval_weighted_f1': '0.6568', 'eval_runtime': '1.098', 'eval_samples_per_second': '973.8', 'eval_steps_per_second': '30.97', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.327490
  Validation Loss     : 0.314180
  Validation Accuracy : 0.658559
  Validation Macro-F1 : 0.658241
==============================================================

{'train_runtime': '326.8', 'train_samples_per_second': '130.8', 'train_steps_per_second': '8.184', 'train_loss': '0.3764', 'epoch': '5'}

[I 2026-09-29 16:27:41,283] Trial 3 finished with value: 0.6582410816881508 and parameters: {'learning_rate': 2.049268011541736e-06, 'weight_decay': 0.06780602616231217, 'warmup_ratio': 0.1287134647448357, 'per_device_train_batch_size': 16}. Best is trial 0 with value: 0.6988869871929208.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'loss': '0.4364', 'grad_norm': '10.33', 'learning_rate': '9.745e-06', 'epoch': '1'}
{'eval_loss': '0.3254', 'eval_accuracy': '0.6436', 'eval_macro_f1': '0.64', 'eval_micro_f1': '0.6436', 'eval_weighted_f1': '0.6384', 'eval_runtime': '1.085', 'eval_samples_per_second': '985.6', 'eval_steps_per_second': '31.35', 'epoch': '1'}

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.436399
  Validation Loss     : 0.325405
  Validation Accuracy : 0.643592
  Validation Macro-F1 : 0.640029
==============================================================

{'loss': '0.309', 'grad_norm': '13.44', 'learning_rate': '7.311e-06', 'epoch': '2'}
{'eval_loss': '0.2613', 'eval_accuracy': '0.6969', 'eval_macro_f1': '0.6979', 'eval_micro_f1': '0.6969', 'eval_weighted_f1': '0.6964', 'eval_runtime': '2.6', 'eval_samples_per_second': '411.1', 'eval_steps_per_second': '13.07', 'epoch': '2'}

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.308969
  Validation Loss     : 0.261311
  Validation Accuracy : 0.696913
  Validation Macro-F1 : 0.697886
==============================================================

{'loss': '0.2681', 'grad_norm': '23.05', 'learning_rate': '4.877e-06', 'epoch': '3'}
{'eval_loss': '0.2661', 'eval_accuracy': '0.6997', 'eval_macro_f1': '0.6961', 'eval_micro_f1': '0.6997', 'eval_weighted_f1': '0.6946', 'eval_runtime': '2.541', 'eval_samples_per_second': '420.6', 'eval_steps_per_second': '13.38', 'epoch': '3'}

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.268101
  Validation Loss     : 0.266127
  Validation Accuracy : 0.699719
  Validation Macro-F1 : 0.696149
==============================================================

{'loss': '0.2424', 'grad_norm': '20.81', 'learning_rate': '2.443e-06', 'epoch': '4'}
{'eval_loss': '0.2592', 'eval_accuracy': '0.7231', 'eval_macro_f1': '0.7215', 'eval_micro_f1': '0.7231', 'eval_weighted_f1': '0.72', 'eval_runtime': '2.043', 'eval_samples_per_second': '523.2', 'eval_steps_per_second': '16.64', 'epoch': '4'}

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.242423
  Validation Loss     : 0.259193
  Validation Accuracy : 0.723106
  Validation Macro-F1 : 0.721477
==============================================================

{'loss': '0.2232', 'grad_norm': '24.57', 'learning_rate': '9.082e-09', 'epoch': '5'}
{'eval_loss': '0.2643', 'eval_accuracy': '0.724', 'eval_macro_f1': '0.7228', 'eval_micro_f1': '0.724', 'eval_weighted_f1': '0.7213', 'eval_runtime': '1.966', 'eval_samples_per_second': '543.7', 'eval_steps_per_second': '17.29', 'epoch': '5'}

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.223193
  Validation Loss     : 0.264268
  Validation Accuracy : 0.724041
  Validation Macro-F1 : 0.722793
==============================================================

{'train_runtime': '280', 'train_samples_per_second': '152.7', 'train_steps_per_second': '4.786', 'train_loss': '0.2958', 'epoch': '5'}

[I 2026-09-29 16:32:23,013] Trial 4 finished with value: 0.7227932435448023 and parameters: {'learning_rate': 1.0952662748632564e-05, 'weight_decay': 0.036503833523887946, 'warmup_ratio': 0.09382169728028272, 'per_device_train_batch_size': 32}. Best is trial 4 with value: 0.7227932435448023.

  BEST OPTUNA Macro-F1: 0.7228
    learning_rate                      : 1.0952662748632564e-05
    weight_decay                       : 0.036503833523887946
    warmup_ratio                       : 0.09382169728028272
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/8
==============================================================
  Train Loss          : 0.375070
  Validation Loss     : 0.328893
  Validation Accuracy : 0.638915
  Validation Macro-F1 : 0.634901
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/8
==============================================================
  Train Loss          : 0.288833
  Validation Loss     : 0.258370
  Validation Accuracy : 0.710945
  Validation Macro-F1 : 0.713948
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/8
==============================================================
  Train Loss          : 0.277015
  Validation Loss     : 0.266245
  Validation Accuracy : 0.708138
  Validation Macro-F1 : 0.705315
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.232260
  Validation Loss     : 0.243156
  Validation Accuracy : 0.733396
  Validation Macro-F1 : 0.732593
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/8
==============================================================
  Train Loss          : 0.211427
  Validation Loss     : 0.253337
  Validation Accuracy : 0.740879
  Validation Macro-F1 : 0.739587
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 6/8
==============================================================
  Train Loss          : 0.200532
  Validation Loss     : 0.251716
  Validation Accuracy : 0.739008
  Validation Macro-F1 : 0.736340
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 7/8
==============================================================
  Train Loss          : 0.167377
  Validation Loss     : 0.251612
  Validation Accuracy : 0.750234
  Validation Macro-F1 : 0.749180
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.184750
  Validation Loss     : 0.267329
  Validation Accuracy : 0.741815
  Validation Macro-F1 : 0.740268
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.184750
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 8/8
==============================================================
  Train Loss          : 0.184750
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8221
  Val   Macro-F1 : 0.7494
  Gap            : +0.0728
  Status         : ⚠️ Potential overfitting (Gap > 0.05)

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.4818
  Balanced Accuracy : 0.4793
  Macro-F1          : 0.4590
  Weighted-F1       : 0.4601
  MCC               : 0.2336
  Macro ROC-AUC     : 0.6982
  Val→Test Gap      : +0.2904

[Bootstrap CI (n=1000)]
  accuracy            : 0.4816 [0.4509, 0.5117]
  macro_f1            : 0.4586 [0.4286, 0.4896]
  weighted_f1         : 0.4599 [0.4281, 0.4917]
  mcc                 : 0.2336 [0.1889, 0.2785]
  balanced_accuracy   : 0.4793 [0.4524, 0.5083]

[Calibration / ECE]
  Positive       : ECE = 0.1617 ⚠️
  Neutral        : ECE = 0.0584 🟠
  Negative       : ECE = 0.1334 ⚠️
  Mean Class ECE  : 0.1178

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8221
  Val   F1  : 0.7494
  Test  F1  : 0.4590
  Train→Val : +0.0728
  Val→Test  : +0.2904
  Status    : ⚠️ Potential overfitting (Gap > 0.05)

[Error Analysis]
  Saved 554 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\mbert_mbert\model
  Tokenizer → D:\Nepali sentiment\tokenizers\mbert_mbert
  Plots     → D:\Nepali sentiment\models\mbert_mbert\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ mbert | Val F1: 0.7494 | Test F1: 0.4590

{'label': 'mBERT',
 'best_hparams': {'learning_rate': 1.0952662748632564e-05,
  'weight_decay': 0.036503833523887946,
  'warmup_ratio': 0.09382169728028272,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.48175865294667913,
 'test_macro_f1': 0.4590033183227021,
 'test_weighted_f1': 0.460072584139464,
 'balanced_accuracy': 0.47933218938469335,
 'mcc': 0.23362427646578765,
 'macro_roc_auc': np.float64(0.6982195722449376),
 'mean_class_ece': 0.11784645140700745,
 'per_class_f1': {'Positive': 0.35490605427974947,
  'Neutral': 0.4438430311231394,
  'Negative': 0.5782608695652174},
 'roc_auc': {'Positive': 0.7355591266319685,
  'Neutral': 0.6341901463262765,
  'Negative': 0.7249094437765677},
 'pr_auc': {'Positive': 0.5797579507734063,
  'Neutral': 0.4877106553824858,
  'Negative': 0.5664016939744188},
 'train_f1': 0.8221199059280296,
 'val_f1': 0.7493672275685673,
 'train_val_gap': 0.07275267835946231,
 'val_test_gap': 0.29036390924586525,
 'gap_status': '⚠️ Potential overfitting (Gap > 0.05)',
 'bootstrap_ci': {'accuracy': (0.48161459307764265,
   0.450865294667914,
   0.5117165575304022),
  'macro_f1': (0.4585984492632515, 0.4286387350767373, 0.4896265609915083),
  'weighted_f1': (0.45993111310353907, 0.4280591095387491, 0.4917333147076825),
  'mcc': (0.23360636519011985, 0.18886774501729625, 0.2784754656974268),
  'balanced_accuracy': (0.4793271166698835,
   0.45236947446418,
   0.5083434325207742),
  'per_class_f1': {'Positive': (0.3553079805240221,
    0.30119682268898607,
    0.40938334200762216),
   'Neutral': (0.44233778624175407, 0.39623624100768695, 0.48941162256856346),
   'Negative': (0.5781495810239783, 0.5404179242756535, 0.6165444862155388)}},
 'ece_scores': {'Positive': 0.1617454641661541,
  'Neutral': 0.058436665527167114,
  'Negative': 0.13335722452770113},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.639098  0.245665  0.354906   346.000000
 Neutral        0.438503  0.449315  0.443843   365.000000
 Negative       0.473310  0.743017  0.578261   358.000000
 accuracy       0.481759  0.481759  0.481759     0.481759
 macro avg      0.516970  0.479332  0.459003  1069.000000
 weighted avg   0.515085  0.481759  0.460073  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.502285   2.576465   0.000000e+00  0.003731     1        NaN
 1   0.492310   2.127223   1.301306e-06  0.093284    25        NaN
 2   0.488439   1.715043   2.656834e-06  0.186567    50        NaN
 3   0.489263   2.276242   4.012362e-06  0.279851    75        NaN
 4   0.487452   2.795462   5.367889e-06  0.373134   100        NaN
 ..       ...        ...            ...       ...   ...        ...
 92  0.184750  19.558899   1.127978e-07  7.929104  2125        NaN
 93       NaN        NaN            NaN  8.000000  2144   0.267329
 94       NaN        NaN            NaN  8.000000  2144        NaN
 95       NaN        NaN            NaN  8.000000  2144        NaN
 96       NaN        NaN            NaN  8.000000  2144        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 ..            ...            ...            ...               ...  ...
 92            NaN            NaN            NaN               NaN  ...
 93       0.741815       0.740268       0.741815          0.738996  ...
 94            NaN            NaN            NaN               NaN  ...
 95            NaN            NaN            NaN               NaN  ...
 96            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 ..             ...                ...       ...           ...           ...
 92             NaN                NaN       NaN           NaN           NaN
 93             NaN                NaN       NaN           NaN           NaN
 94             NaN                NaN       NaN           NaN           NaN
 95           0.821           0.819595       NaN           NaN           NaN
 96             NaN                NaN  0.251734      0.750234      0.749367

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 ..           ...              ...          ...                     ...
 92           NaN              NaN          NaN                     NaN
 93           NaN              NaN          NaN                     NaN
 94           NaN              NaN          NaN                     NaN
 95           NaN              NaN          NaN                     NaN
 96      0.750234         0.748017       2.3122                 462.339

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 ..                   ...
 92                   NaN
 93                   NaN
 94                   NaN
 95                   NaN
 96                14.705

 [97 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                2       0.022221      0.218579       0.759200
 1              0                0       0.790935      0.184230       0.024836
 2              0                2       0.038872      0.458991       0.502137
 3              1                1       0.108052      0.555201       0.336747
 4              2                1       0.132998      0.666249       0.200753
 ...          ...              ...            ...           ...            ...
 1064           2                2       0.036011      0.413735       0.550255
 1065           0                2       0.025843      0.224783       0.749374
 1066           0                0       0.803988      0.189478       0.006534
 1067           1                0       0.502556      0.392923       0.104522
 1068           1                2       0.027133      0.161116       0.811750

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 488                          बिपुल चेत्त्री इस नेपाल 🙏   Neutral  Negative
 273                भगवान होला हाम्रो थ्वो मन्क्षे एस्त   Neutral  Negative
 72   यो ज्ञानी हित येह हेरेको अनुसार जपनेसे कोरेअन ...  Positive  Negative
 419                             गनेंद्र दै इस पत्रोटिक  Positive  Negative
 379                                      केनोपमा चौदरी  Positive  Negative
 ..                                                 ...       ...       ...
 357                         नेपाली मुस्लिम कसरि सक्क्ष   Neutral  Positive
 275                           राम्रू नानी बथॊओ पने....  Positive   Neutral
 76                   मर शिशिर भट्ट इस अ मर .शिशिर भट्ट  Positive   Neutral
 33             सिको वयक्ष g.bob को महतो ठ नोई रोइन्क्ष  Negative  Positive
 214            इस इन तपाई जति भयानी हुदैन एकदम हुन्क्ष   Neutral  Positive

      confidence  token_length
 488    0.876596            11
 273    0.863217            16
 72     0.862645            44
 419    0.847536            13
 379    0.844980            10
 ..          ...           ...
 357    0.359166            11
 275    0.358789            14
 76     0.354412            21
 33     0.354383            24
 214    0.351032            21

 [554 rows x 5 columns]}

In [28]:
# Save original epochs value
original_epochs = EPOCHS

# Set epochs to 5 for this run
EPOCHS = 5

# Run XLM-R with Optuna-found HPs and 5 epochs
run_model(
    "xlmr",
    run_name="xlmr_fixed_best_hps_5ep",
    use_optuna=False,       # Optuna already done → use fixed HPs
    use_llrd=False,
    learning_rate=1.0952662748632564e-05,      # from Optuna: 1.0952662748632564e-05
    weight_decay=0.036503833523887946,           # from Optuna: 0.036503833523887946
    warmup_ratio=0.09382169728028272
,           # from Optuna: 0.09382169728028272
    batch_size=32,                 # from Optuna: 32.0
)

# Restore original epochs for future runs
EPOCHS = original_epochs

################################################################################
  RUNNING: XLM-RoBERTa | Run: xlmr_fixed_best_hps_5ep
  Model output : D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps_5ep
  Checkpoints  : D:\Nepali sentiment\training_checkpoints\xlmr_fixed_best_hps_5ep
  Tokenizer    : D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr_fixed_best_hps_5ep
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): XLM-RoBERTa
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 1.0952662748632564e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 36 tokens
     95.0% → 46 tokens
     97.0% → 53 tokens
     98.0% → 56 tokens
     99.0% → 63 tokens
     99.5% → 70 tokens
    100.0% → 106 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8549 | Val: 1069 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 1.0952662748632564e-05
    weight_decay                       : 0.036503833523887946
    warmup_ratio                       : 0.09382169728028272
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/5
==============================================================
  Train Loss          : 0.331015
  Validation Loss     : 0.260114
  Validation Accuracy : 0.701590
  Validation Macro-F1 : 0.698105
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/5
==============================================================
  Train Loss          : 0.226462
  Validation Loss     : 0.234572
  Validation Accuracy : 0.751169
  Validation Macro-F1 : 0.745946
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/5
==============================================================
  Train Loss          : 0.220405
  Validation Loss     : 0.203900
  Validation Accuracy : 0.768007
  Validation Macro-F1 : 0.761587
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/5
==============================================================
  Train Loss          : 0.173720
  Validation Loss     : 0.201091
  Validation Accuracy : 0.779233
  Validation Macro-F1 : 0.777009
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.154822
  Validation Loss     : 0.206196
  Validation Accuracy : 0.789523
  Validation Macro-F1 : 0.788949
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.154822
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 5/5
==============================================================
  Train Loss          : 0.154822
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8190
  Val   Macro-F1 : 0.7889
  Gap            : +0.0300
  Status         : ✅ Healthy generalization

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.5285
  Balanced Accuracy : 0.5269
  Macro-F1          : 0.5226
  Weighted-F1       : 0.5225
  MCC               : 0.3033
  Macro ROC-AUC     : 0.7495
  Val→Test Gap      : +0.2664

[Bootstrap CI (n=1000)]
  accuracy            : 0.5283 [0.5005, 0.5575]
  macro_f1            : 0.5217 [0.4942, 0.5515]
  weighted_f1         : 0.5220 [0.4939, 0.5521]
  mcc                 : 0.3031 [0.2610, 0.3463]
  balanced_accuracy   : 0.5268 [0.4993, 0.5550]

[Calibration / ECE]
  Positive       : ECE = 0.1627 ⚠️
  Neutral        : ECE = 0.0836 🟠
  Negative       : ECE = 0.1151 ⚠️
  Mean Class ECE  : 0.1204

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8190
  Val   F1  : 0.7889
  Test  F1  : 0.5226
  Train→Val : +0.0300
  Val→Test  : +0.2664
  Status    : ✅ Healthy generalization

[Error Analysis]
  Saved 504 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps_5ep\model
  Tokenizer → D:\Nepali sentiment\tokenizers\xlm-roberta-base_xlmr_fixed_best_hps_5ep
  Plots     → D:\Nepali sentiment\models\xlm-roberta-base_xlmr_fixed_best_hps_5ep\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ xlmr_fixed_best_hps_5ep | Val F1: 0.7889 | Test F1: 0.5226

In [ ]:
# Configuration for XLM-RoBERTa with best hyperparameters
xlmr_config = {
    'key': 'xlmr',
    'label': 'XLM-RoBERTa',
    'checkpoint': 'xlm-roberta-base',
    'save_dir': './results_xlmr',
    'output_dir': './runs/xlmr',
    'tok_dir': './tokenizers_xlmr',
    
    # Disable Optuna since we're using fixed best hyperparameters
    'use_optuna': False,
    
    # Optional settings
    'use_llrd': False,           # Layer-wise learning rate decay
    'layer_decay': 0.9,
    'use_custom_model': False,  # Use standard AutoModel
    
    # Best hyperparameters found
    'learning_rate': 4.33e-06,
    'weight_decay': 0.190635718,
    'warmup_ratio': 0.159799091,
    'batch_size': 16,
}

# Run the pipeline
result = run_training_pipeline_optimized(
    config=xlmr_config,
    train_df=train_df,
    val_df=val_df,
    test_df=test_df,
    class_weights=class_weights,
    report_to='none',
)

print(f"\n✅ XLM-RoBERTa Training Complete!")
print(f"Test Macro-F1: {result['test_macro_f1']:.4f}")
print(f"Test Accuracy: {result['test_accuracy']:.4f}")

In [ ]:
# import sys
# import io
# import faulthandler

# def _watchdog_arm(minutes):
#     if minutes and minutes > 0:
#         try:
#             # Jupyter's sys.stderr is an OutStream and lacks fileno().
#             # We attempt to use the original OS-level stderr stream instead.
#             if hasattr(sys, '__stderr__') and sys.__stderr__ is not None:
#                 faulthandler.dump_traceback_later(
#                     minutes * 60, 
#                     repeat=True, 
#                     file=sys.__stderr__
#                 )
#             else:
#                 raise io.UnsupportedOperation("No original stderr available")
                
#             _log(f"  ⏱️  Watchdog armed: stack dump every {minutes} min if stalled.")
            
#         except (io.UnsupportedOperation, AttributeError, ValueError, OSError):
#             # Fallback for environments where faulthandler cannot get a valid file descriptor
#             _log(f"  ⏱️  Watchdog disabled: Jupyter/IPython environment does not support faulthandler fileno().")

In [ ]:
run_model("xlmr", run_name="smoke", debug_mode=True)

################################################################################
  RUNNING: XLM-RoBERTa | Run: smoke
  Model output : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\xlm-roberta-base_smoke
  Checkpoints  : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\training_checkpoints\smoke
  Tokenizer    : D:\FinalYear_Sentiment_Training\English_Sentiment_Models\tokenizers\xlm-roberta-base_smoke
################################################################################

================================================================================
  PIPELINE v6.1 (SPEED-OPTIMIZED): XLM-RoBERTa
================================================================================
  Seed            : 42 (single)
  Optuna          : False
  LLRD            : False
  Grad Ckpt       : False
  Batch/Accum     : 32/1
  Learning Rate   : 2e-05

[1] Strict Data QA
  ✅ Passed strict QA

[2] Tokenization & Length Analysis

  [Token Length Distribution]  (sampled 5000)
     90.0% → 40 tokens
     95.0% → 49 tokens
     97.0% → 56 tokens
     98.0% → 59 tokens
     99.0% → 67 tokens
     99.5% → 73 tokens
    100.0% → 113 tokens
    Current MAX_LEN = 256
    Truncation Rate = 0.00%
  Train: 8544 | Val: 1068 | Test: 1069

  Optuna disabled → Using fixed hyperparameters.
    learning_rate                      : 2e-05
    weight_decay                       : 0.15
    warmup_ratio                       : 0.1
    per_device_train_batch_size        : 32

--------------------------------------------------------------------------------
  PHASE 2: FINAL TRAINING (single seed)
--------------------------------------------------------------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

==============================================================
  📊 EPOCH 1/8
==============================================================
  Train Loss          : 0.245173
  Validation Loss     : 0.255154
  Validation Accuracy : 0.754682
  Validation Macro-F1 : 0.754953
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 2/8
==============================================================
  Train Loss          : 0.193813
  Validation Loss     : 0.222563
  Validation Accuracy : 0.798689
  Validation Macro-F1 : 0.800266
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 3/8
==============================================================
  Train Loss          : 0.147140
  Validation Loss     : 0.227670
  Validation Accuracy : 0.785581
  Validation Macro-F1 : 0.785199
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.111257
  Validation Loss     : 0.255747
  Validation Accuracy : 0.801498
  Validation Macro-F1 : 0.799584
==============================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  ✅ Training complete. Best checkpoint loaded.

[Train vs Validation Diagnostics]

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.111257
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

==============================================================
  📊 EPOCH 4/8
==============================================================
  Train Loss          : 0.111257
==============================================================

[transformers] early stopping required metric_for_best_model, but did not find eval_macro_f1 so early stopping is disabled

  Train Macro-F1 (1000 samples): 0.8459
  Val   Macro-F1 : 0.8003
  Gap            : +0.0456
  Status         : ✅ Healthy generalization

--------------------------------------------------------------------------------
  INDEPENDENT TEST EVALUATION
--------------------------------------------------------------------------------

  Accuracy          : 0.8026
  Balanced Accuracy : 0.8034
  Macro-F1          : 0.8022
  Weighted-F1       : 0.8016
  MCC               : 0.7042
  Macro ROC-AUC     : 0.9323
  Val→Test Gap      : -0.0019

[Bootstrap CI (n=1000)]
  accuracy            : 0.8025 [0.7774, 0.8279]
  macro_f1            : 0.8019 [0.7772, 0.8271]
  weighted_f1         : 0.8015 [0.7763, 0.8272]
  mcc                 : 0.7041 [0.6665, 0.7426]
  balanced_accuracy   : 0.8034 [0.7792, 0.8282]

[Calibration / ECE]
  Positive       : ECE = 0.0572 🟠
  Neutral        : ECE = 0.1284 ⚠️
  Negative       : ECE = 0.0944 🟠
  Mean Class ECE  : 0.0933

================================================================================
  GENERALIZATION ANALYSIS
================================================================================
  Train F1  : 0.8459
  Val   F1  : 0.8003
  Test  F1  : 0.8022
  Train→Val : +0.0456
  Val→Test  : -0.0019
  Status    : ✅ Healthy generalization

[Error Analysis]
  Saved 211 errors → error_analysis.csv

[Saving Plots]

[Saving Artifacts]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model     → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\xlm-roberta-base_smoke\model
  Tokenizer → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\tokenizers\xlm-roberta-base_smoke
  Plots     → D:\FinalYear_Sentiment_Training\English_Sentiment_Models\models\xlm-roberta-base_smoke\plots

================================================================================
  PIPELINE v6.1 COMPLETED SUCCESSFULLY
================================================================================

✅ smoke | Val F1: 0.8003 | Test F1: 0.8022

{'label': 'XLM-RoBERTa',
 'best_hparams': {'learning_rate': 2e-05,
  'weight_decay': 0.15,
  'warmup_ratio': 0.1,
  'per_device_train_batch_size': 32},
 'test_accuracy': 0.8026192703461179,
 'test_macro_f1': 0.802214299792737,
 'test_weighted_f1': 0.8016172864571386,
 'balanced_accuracy': 0.8034488370928236,
 'mcc': 0.7042253545985974,
 'macro_roc_auc': np.float64(0.9322666840748416),
 'mean_class_ece': 0.09330721417895575,
 'per_class_f1': {'Positive': 0.8758716875871687,
  'Neutral': 0.7223796033994334,
  'Negative': 0.8083916083916084},
 'roc_auc': {'Positive': 0.9686564788283984,
  'Neutral': 0.8847401959628818,
  'Negative': 0.9434033774332445},
 'pr_auc': {'Positive': 0.9443405674989013,
  'Neutral': 0.7720850188758724,
  'Negative': 0.9049747602118722},
 'train_f1': 0.8458756454143446,
 'val_f1': 0.8002656992678924,
 'train_val_gap': 0.045609946146452196,
 'val_test_gap': -0.0019486005248445792,
 'gap_status': '✅ Healthy generalization',
 'bootstrap_ci': {'accuracy': (0.8025032740879326,
   0.7773620205799813,
   0.8278999064546305),
  'macro_f1': (0.8018649050161547, 0.7772411438671931, 0.8271481548153872),
  'weighted_f1': (0.801457167976364, 0.7763156487131011, 0.8272199944273564),
  'mcc': (0.7040672219123247, 0.6664822220786364, 0.7425652383791752),
  'balanced_accuracy': (0.8033517891965541,
   0.7791714678708344,
   0.8281659740978597),
  'per_class_f1': {'Positive': (0.8753380379985974,
    0.8482184596943363,
    0.8996213716627792),
   'Neutral': (0.7217070543599391, 0.6857798665805145, 0.7604028206839499),
   'Negative': (0.8085496226899275, 0.775935292777398, 0.8424166747532637)}},
 'ece_scores': {'Positive': 0.0571891629425469,
  'Neutral': 0.1283538176480357,
  'Negative': 0.09437866194628465},
 'classification_report':               precision    recall  f1-score      support
 Positive       0.853261  0.899713  0.875872   349.000000
 Neutral        0.732759  0.712291  0.722380   358.000000
 Negative       0.818697  0.798343  0.808392   362.000000
 accuracy       0.802619  0.802619  0.802619     0.802619
 macro avg      0.801572  0.803449  0.802214  1069.000000
 weighted avg   0.801201  0.802619  0.801617  1069.000000,
 'history':         loss  grad_norm  learning_rate     epoch  step  eval_loss  \
 0   0.511750   1.751100       0.000000  0.003745     1        NaN
 1   0.518844   1.271965       0.000002  0.093633    25        NaN
 2   0.502729   3.447104       0.000005  0.187266    50        NaN
 3   0.471039   2.867075       0.000007  0.280899    75        NaN
 4   0.403864  10.957682       0.000009  0.374532   100        NaN
 5   0.306698   5.629416       0.000012  0.468165   125        NaN
 6   0.253337  29.607105       0.000014  0.561798   150        NaN
 7   0.294576   8.335556       0.000016  0.655431   175        NaN
 8   0.253918  15.940649       0.000019  0.749064   200        NaN
 9   0.223222   9.191548       0.000020  0.842697   225        NaN
 10  0.245173   6.968454       0.000020  0.936330   250        NaN
 11       NaN        NaN            NaN  1.000000   267   0.255154
 12  0.211904   4.473039       0.000019  1.029963   275        NaN
 13  0.179970  12.926391       0.000019  1.123596   300        NaN
 14  0.238558  12.438794       0.000019  1.217228   325        NaN
 15  0.194522   5.539485       0.000019  1.310861   350        NaN
 16  0.191726   6.229585       0.000018  1.404494   375        NaN
 17  0.172039   6.697267       0.000018  1.498127   400        NaN
 18  0.200028   6.983380       0.000018  1.591760   425        NaN
 19  0.187547   4.445410       0.000018  1.685393   450        NaN
 20  0.184584  14.713166       0.000017  1.779026   475        NaN
 21  0.186508  10.838277       0.000017  1.872659   500        NaN
 22  0.193813   6.108217       0.000017  1.966292   525        NaN
 23       NaN        NaN            NaN  2.000000   534   0.222563
 24  0.171489   6.609253       0.000017  2.059925   550        NaN
 25  0.152924   6.423084       0.000016  2.153558   575        NaN
 26  0.131361   4.110461       0.000016  2.247191   600        NaN
 27  0.132634   5.759549       0.000016  2.340824   625        NaN
 28  0.129216   2.458573       0.000015  2.434457   650        NaN
 29  0.114840   6.603646       0.000015  2.528090   675        NaN
 30  0.156038   5.603750       0.000015  2.621723   700        NaN
 31  0.159651   4.435714       0.000015  2.715356   725        NaN
 32  0.143671   2.488508       0.000014  2.808989   750        NaN
 33  0.139530  18.091988       0.000014  2.902622   775        NaN
 34  0.147140   8.631157       0.000014  2.996255   800        NaN
 35       NaN        NaN            NaN  3.000000   801   0.227670
 36  0.100540   4.001151       0.000014  3.089888   825        NaN
 37  0.107943   9.328287       0.000013  3.183521   850        NaN
 38  0.087983   1.976404       0.000013  3.277154   875        NaN
 39  0.113704   5.047396       0.000013  3.370787   900        NaN
 40  0.116236   4.384682       0.000013  3.464419   925        NaN
 41  0.102522   3.281589       0.000012  3.558052   950        NaN
 42  0.119567   3.374441       0.000012  3.651685   975        NaN
 43  0.112541   2.619940       0.000012  3.745318  1000        NaN
 44  0.094249   6.223597       0.000012  3.838951  1025        NaN
 45  0.111257   7.525393       0.000011  3.932584  1050        NaN
 46       NaN        NaN            NaN  4.000000  1068   0.255747
 47       NaN        NaN            NaN  4.000000  1068        NaN
 48       NaN        NaN            NaN  4.000000  1068        NaN
 49       NaN        NaN            NaN  4.000000  1068        NaN

     eval_accuracy  eval_macro_f1  eval_micro_f1  eval_weighted_f1  ...  \
 0             NaN            NaN            NaN               NaN  ...
 1             NaN            NaN            NaN               NaN  ...
 2             NaN            NaN            NaN               NaN  ...
 3             NaN            NaN            NaN               NaN  ...
 4             NaN            NaN            NaN               NaN  ...
 5             NaN            NaN            NaN               NaN  ...
 6             NaN            NaN            NaN               NaN  ...
 7             NaN            NaN            NaN               NaN  ...
 8             NaN            NaN            NaN               NaN  ...
 9             NaN            NaN            NaN               NaN  ...
 10            NaN            NaN            NaN               NaN  ...
 11       0.754682       0.754953       0.754682          0.753930  ...
 12            NaN            NaN            NaN               NaN  ...
 13            NaN            NaN            NaN               NaN  ...
 14            NaN            NaN            NaN               NaN  ...
 15            NaN            NaN            NaN               NaN  ...
 16            NaN            NaN            NaN               NaN  ...
 17            NaN            NaN            NaN               NaN  ...
 18            NaN            NaN            NaN               NaN  ...
 19            NaN            NaN            NaN               NaN  ...
 20            NaN            NaN            NaN               NaN  ...
 21            NaN            NaN            NaN               NaN  ...
 22            NaN            NaN            NaN               NaN  ...
 23       0.798689       0.800266       0.798689          0.799560  ...
 24            NaN            NaN            NaN               NaN  ...
 25            NaN            NaN            NaN               NaN  ...
 26            NaN            NaN            NaN               NaN  ...
 27            NaN            NaN            NaN               NaN  ...
 28            NaN            NaN            NaN               NaN  ...
 29            NaN            NaN            NaN               NaN  ...
 30            NaN            NaN            NaN               NaN  ...
 31            NaN            NaN            NaN               NaN  ...
 32            NaN            NaN            NaN               NaN  ...
 33            NaN            NaN            NaN               NaN  ...
 34            NaN            NaN            NaN               NaN  ...
 35       0.785581       0.785199       0.785581          0.784624  ...
 36            NaN            NaN            NaN               NaN  ...
 37            NaN            NaN            NaN               NaN  ...
 38            NaN            NaN            NaN               NaN  ...
 39            NaN            NaN            NaN               NaN  ...
 40            NaN            NaN            NaN               NaN  ...
 41            NaN            NaN            NaN               NaN  ...
 42            NaN            NaN            NaN               NaN  ...
 43            NaN            NaN            NaN               NaN  ...
 44            NaN            NaN            NaN               NaN  ...
 45            NaN            NaN            NaN               NaN  ...
 46       0.801498       0.799584       0.801498          0.799040  ...
 47            NaN            NaN            NaN               NaN  ...
 48            NaN            NaN            NaN               NaN  ...
 49            NaN            NaN            NaN               NaN  ...

     train_micro_f1  train_weighted_f1  val_loss  val_accuracy  val_macro_f1  \
 0              NaN                NaN       NaN           NaN           NaN
 1              NaN                NaN       NaN           NaN           NaN
 2              NaN                NaN       NaN           NaN           NaN
 3              NaN                NaN       NaN           NaN           NaN
 4              NaN                NaN       NaN           NaN           NaN
 5              NaN                NaN       NaN           NaN           NaN
 6              NaN                NaN       NaN           NaN           NaN
 7              NaN                NaN       NaN           NaN           NaN
 8              NaN                NaN       NaN           NaN           NaN
 9              NaN                NaN       NaN           NaN           NaN
 10             NaN                NaN       NaN           NaN           NaN
 11             NaN                NaN       NaN           NaN           NaN
 12             NaN                NaN       NaN           NaN           NaN
 13             NaN                NaN       NaN           NaN           NaN
 14             NaN                NaN       NaN           NaN           NaN
 15             NaN                NaN       NaN           NaN           NaN
 16             NaN                NaN       NaN           NaN           NaN
 17             NaN                NaN       NaN           NaN           NaN
 18             NaN                NaN       NaN           NaN           NaN
 19             NaN                NaN       NaN           NaN           NaN
 20             NaN                NaN       NaN           NaN           NaN
 21             NaN                NaN       NaN           NaN           NaN
 22             NaN                NaN       NaN           NaN           NaN
 23             NaN                NaN       NaN           NaN           NaN
 24             NaN                NaN       NaN           NaN           NaN
 25             NaN                NaN       NaN           NaN           NaN
 26             NaN                NaN       NaN           NaN           NaN
 27             NaN                NaN       NaN           NaN           NaN
 28             NaN                NaN       NaN           NaN           NaN
 29             NaN                NaN       NaN           NaN           NaN
 30             NaN                NaN       NaN           NaN           NaN
 31             NaN                NaN       NaN           NaN           NaN
 32             NaN                NaN       NaN           NaN           NaN
 33             NaN                NaN       NaN           NaN           NaN
 34             NaN                NaN       NaN           NaN           NaN
 35             NaN                NaN       NaN           NaN           NaN
 36             NaN                NaN       NaN           NaN           NaN
 37             NaN                NaN       NaN           NaN           NaN
 38             NaN                NaN       NaN           NaN           NaN
 39             NaN                NaN       NaN           NaN           NaN
 40             NaN                NaN       NaN           NaN           NaN
 41             NaN                NaN       NaN           NaN           NaN
 42             NaN                NaN       NaN           NaN           NaN
 43             NaN                NaN       NaN           NaN           NaN
 44             NaN                NaN       NaN           NaN           NaN
 45             NaN                NaN       NaN           NaN           NaN
 46             NaN                NaN       NaN           NaN           NaN
 47             NaN                NaN       NaN           NaN           NaN
 48           0.845           0.844035       NaN           NaN           NaN
 49             NaN                NaN  0.222563      0.798689      0.800266

     val_micro_f1  val_weighted_f1  val_runtime  val_samples_per_second  \
 0            NaN              NaN          NaN                     NaN
 1            NaN              NaN          NaN                     NaN
 2            NaN              NaN          NaN                     NaN
 3            NaN              NaN          NaN                     NaN
 4            NaN              NaN          NaN                     NaN
 5            NaN              NaN          NaN                     NaN
 6            NaN              NaN          NaN                     NaN
 7            NaN              NaN          NaN                     NaN
 8            NaN              NaN          NaN                     NaN
 9            NaN              NaN          NaN                     NaN
 10           NaN              NaN          NaN                     NaN
 11           NaN              NaN          NaN                     NaN
 12           NaN              NaN          NaN                     NaN
 13           NaN              NaN          NaN                     NaN
 14           NaN              NaN          NaN                     NaN
 15           NaN              NaN          NaN                     NaN
 16           NaN              NaN          NaN                     NaN
 17           NaN              NaN          NaN                     NaN
 18           NaN              NaN          NaN                     NaN
 19           NaN              NaN          NaN                     NaN
 20           NaN              NaN          NaN                     NaN
 21           NaN              NaN          NaN                     NaN
 22           NaN              NaN          NaN                     NaN
 23           NaN              NaN          NaN                     NaN
 24           NaN              NaN          NaN                     NaN
 25           NaN              NaN          NaN                     NaN
 26           NaN              NaN          NaN                     NaN
 27           NaN              NaN          NaN                     NaN
 28           NaN              NaN          NaN                     NaN
 29           NaN              NaN          NaN                     NaN
 30           NaN              NaN          NaN                     NaN
 31           NaN              NaN          NaN                     NaN
 32           NaN              NaN          NaN                     NaN
 33           NaN              NaN          NaN                     NaN
 34           NaN              NaN          NaN                     NaN
 35           NaN              NaN          NaN                     NaN
 36           NaN              NaN          NaN                     NaN
 37           NaN              NaN          NaN                     NaN
 38           NaN              NaN          NaN                     NaN
 39           NaN              NaN          NaN                     NaN
 40           NaN              NaN          NaN                     NaN
 41           NaN              NaN          NaN                     NaN
 42           NaN              NaN          NaN                     NaN
 43           NaN              NaN          NaN                     NaN
 44           NaN              NaN          NaN                     NaN
 45           NaN              NaN          NaN                     NaN
 46           NaN              NaN          NaN                     NaN
 47           NaN              NaN          NaN                     NaN
 48           NaN              NaN          NaN                     NaN
 49      0.798689          0.79956       0.8678                1230.688

     val_steps_per_second
 0                    NaN
 1                    NaN
 2                    NaN
 3                    NaN
 4                    NaN
 5                    NaN
 6                    NaN
 7                    NaN
 8                    NaN
 9                    NaN
 10                   NaN
 11                   NaN
 12                   NaN
 13                   NaN
 14                   NaN
 15                   NaN
 16                   NaN
 17                   NaN
 18                   NaN
 19                   NaN
 20                   NaN
 21                   NaN
 22                   NaN
 23                   NaN
 24                   NaN
 25                   NaN
 26                   NaN
 27                   NaN
 28                   NaN
 29                   NaN
 30                   NaN
 31                   NaN
 32                   NaN
 33                   NaN
 34                   NaN
 35                   NaN
 36                   NaN
 37                   NaN
 38                   NaN
 39                   NaN
 40                   NaN
 41                   NaN
 42                   NaN
 43                   NaN
 44                   NaN
 45                   NaN
 46                   NaN
 47                   NaN
 48                   NaN
 49                39.179

 [50 rows x 30 columns],
 'predictions_df':       true_label  predicted_label  prob_Positive  prob_Neutral  prob_Negative
 0              0                0       0.809782      0.176501       0.013717
 1              2                2       0.023835      0.311515       0.664650
 2              0                1       0.043012      0.830817       0.126172
 3              1                1       0.347865      0.441248       0.210888
 4              2                2       0.032446      0.193653       0.773901
 ...          ...              ...            ...           ...            ...
 1064           2                2       0.033599      0.307170       0.659231
 1065           2                2       0.017761      0.351217       0.631022
 1066           2                0       0.552117      0.316744       0.131139
 1067           0                0       0.669510      0.257113       0.073377
 1068           1                1       0.347201      0.621375       0.031424

 [1069 rows x 5 columns],
 'errors_df':                                                   text      true      pred  \
 75         Do I need to teach you a lesson, Kapil sir?  Negative   Neutral
 60   What is the fact? G-Bob and his family might b...  Positive   Neutral
 0    Omg, along with this pain, the background musi...  Positive   Neutral
 118  Now, I wonder on which day the divorce will ha...  Negative   Neutral
 8    Such an innocent boy Laure, love you both, bes...   Neutral  Positive
 ..                                                 ...       ...       ...
 189                        Let all be youth power now.  Positive   Neutral
 185  Such monitoring should be everywhere and safet...  Negative  Positive

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

if 'class_weights' not in globals():
    classes = np.unique(train_df['label'].astype(int).to_numpy())
    cw = compute_class_weight(
        class_weight='balanced',
        classes=classes,
        y=train_df['label'].astype(int).to_numpy(),
    )
    class_weights = torch.tensor(cw, dtype=torch.float)
    print(f"Class weights (Pos / Neu / Neg): {class_weights.numpy().round(4)}")

## 11. Disk Space Cleanup (safety net)

`run_sentiment_pipeline` already cleans up its own local checkpoint dir after each run; this cell is just a safety net in case a run was interrupted.

In [ ]:
import glob

for directory in glob.glob('./results_*'):
    if os.path.exists(directory):
        print(f"Removing {directory} to free up space...")
        shutil.rmtree(directory)

print("\nDisk cleanup complete.")

Disk cleanup complete.

## 12. Comparison Table Against Thapa et al. (2023)

Built dynamically from the `results` dict — every entry reflects a model that was actually trained and evaluated in this notebook, not a remembered/hard-coded score. Run only the models you care about above; this table adapts to whatever is in `results`.

In [23]:
PAPER_RESULTS = {
    'mBERT (paper)' : 0.61,
    'MuRIL (paper)' : 0.65,
    'XLM-R (paper)' : 0.67,
}

OUR_RESULTS = {
    f"{cfg['label']} (ours)": all_results[cfg['key']]['macro_f1']
    for cfg in MODEL_CONFIGS if cfg['key'] in all_results
}

all_scores = {**PAPER_RESULTS, **OUR_RESULTS}

print("\n📊 Macro-F1 Comparison")
print("-" * 50)
for name, score in sorted(all_scores.items(), key=lambda x: x[1], reverse=True):
    bar = '█' * int(score * 40)
    print(f"{name:<24} {score:.4f}  {bar}")

summary_df = pd.DataFrame([
    {
        'Model'          : cfg['label'],
        'Checkpoint'     : cfg['checkpoint'],
        'Macro F1 (ours)': all_results[cfg['key']]['macro_f1'],
        'Accuracy (ours)': all_results[cfg['key']]['accuracy'],
    }
    for cfg in MODEL_CONFIGS if cfg['key'] in all_results
]).sort_values('Macro F1 (ours)', ascending=False).reset_index(drop=True)

summary_df

KeyError: 'macro_f1'

```markdown
## 12.1. Visualizing Training & Validation Loss

The following function extracts the loss history from each model's `results` entry and plots them to check for convergence or overfitting.
```

In [24]:
plot_labels = list(all_scores.keys())
plot_scores = list(all_scores.values())
plot_colors = ['#4C72B0' if '(ours)' in l else '#B0B0B0' for l in plot_labels]

order = np.argsort(plot_scores)[::-1]
plot_labels = [plot_labels[i] for i in order]
plot_scores = [plot_scores[i] for i in order]
plot_colors = [plot_colors[i] for i in order]

plt.figure(figsize=(8, 5))
plt.barh(plot_labels, plot_scores, color=plot_colors)
plt.xlabel('Macro F1')
plt.title('Macro-F1: Paper Baselines vs. Ours')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('macro_f1_comparison.png', dpi=150)
plt.show()

NameError: name 'all_scores' is not defined

In [25]:
def plot_loss_curves(results_dict, smooth=True, window=5):
    if not results_dict:
        print("No results found. Please train at least one model first.")
        return

    num_models = len(results_dict)
    fig, axes = plt.subplots(1, num_models, figsize=(6 * num_models, 5), sharey=True)
    if num_models == 1: axes = [axes]

    for i, (model_key, data) in enumerate(results_dict.items()):
        history = data['history']

        train_loss = [log['loss'] for log in history if 'loss' in log]
        train_steps = [log['epoch'] for log in history if 'loss' in log]
        val_loss = [log['eval_loss'] for log in history if 'eval_loss' in log]
        val_epochs = [log['epoch'] for log in history if 'eval_loss' in log]

        ax = axes[i]

        # Original noisy training loss in light color
        ax.plot(train_steps, train_loss, color='blue', alpha=0.2, label='Raw Train Loss')

        if smooth and len(train_loss) > window:
            # Apply moving average to smooth out fluctuations
            smoothed_loss = np.convolve(train_loss, np.ones(window)/window, mode='valid')
            ax.plot(train_steps[window-1:], smoothed_loss, color='blue', linewidth=2, label='Smoothed Train')

        ax.plot(val_epochs, val_loss, label='Validation Loss', color='red', marker='o', linewidth=2)

        ax.set_title(f'Loss Trends: {model_key}')
        ax.set_xlabel('Epochs')
        ax.set_ylabel('Loss')
        ax.legend()
        ax.grid(True, linestyle='--', alpha=0.5)

    plt.tight_layout()
    plt.show()

# Re-run with smoothing to see the real trend
plot_loss_curves(results, smooth=True, window=10)

NameError: name 'results' is not defined

## 13. Inference Helper

Quick function to run inference on new text using any model that's been trained above. Reloads the model/tokenizer from its saved Drive directory (since `run_sentiment_pipeline` frees GPU memory after each run by default).

In [26]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def load_trained(model_key: str):
    """Reload a trained model + tokenizer from Drive using its entry in `results`."""
    r = results[model_key]
    tok = AutoTokenizer.from_pretrained(r['tok_save'])
    mdl = AutoModelForSequenceClassification.from_pretrained(r['save_dir']).to(device)
    return mdl, tok

def predict_sentiment(texts, model, tokenizer, device='cuda', batch_size=32):
    """
    Predict sentiment for a list of texts.
    Returns list of (label_str, confidence) tuples.
    """
    model.eval()
    results_out = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i : i + batch_size]
        enc = tokenizer(
            batch_texts, truncation=True, padding=True, max_length=MAX_LEN, return_tensors='pt',
        ).to(device)

        with torch.no_grad():
            logits = model(**enc).logits

        probs = torch.softmax(logits, dim=-1).cpu().numpy()
        preds = probs.argmax(axis=-1)

        for pred, prob in zip(preds, probs):
            results_out.append((ID2LABEL[pred], round(float(prob[pred]), 4)))

    return results_out


# ── Quick smoke test — uses whichever model in `results` scored highest ──────
if results:
    best_key = max(results, key=lambda k: results[k]['macro_f1'])
    demo_model, demo_tokenizer = load_trained(best_key)

    sample_texts  = val_df['input_text'].head(5).tolist()
    sample_labels = val_df['sentiment_raw'].head(5).tolist()

    predictions = predict_sentiment(sample_texts, demo_model, demo_tokenizer, device=device)
    print(f"Using best model so far: {best_key} (macro F1 = {results[best_key]['macro_f1']:.4f})\n")
    print(f"{'Text':<60} {'True':>10} {'Pred':>10} {'Conf':>6}")
    print("-" * 90)
    for text, true_lbl, (pred_lbl, conf) in zip(sample_texts, sample_labels, predictions):
        match = '✓' if true_lbl == pred_lbl else '✗'
        print(f"{str(text)[:58]:<60} {true_lbl:>10} {pred_lbl:>10} {conf:>6.3f} {match}")
else:
    print("No models trained yet — run one of the `run_sentiment_pipeline(...)` cells above first.")

NameError: name 'results' is not defined